# Form implementation generated from reading ui file 'D:\TuduylaptrinhN1\Metro\UI\Customer\Dangky.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegisterWindow(object):
    def setupUi(self, RegisterWindow):
        RegisterWindow.setObjectName("RegisterWindow")
        RegisterWindow.resize(450, 703)
        RegisterWindow.setStyleSheet("\n"
"    QMainWindow { background-color: #E8F6FD; }\n"
"    #central_panel { background-color: #FFFFFF; border: 1px solid #BEE3F8; border-radius: 16px; }\n"
"    QLabel#lbl_logo_icon { background-color: #0288D1; border-radius: 38px; font-size: 30px; border: 2px solid #29B6F6; }\n"
"    QLabel#lbl_logo { color: #0A4D7A; font-weight: bold; font-size: 22px; }\n"
"    QLabel#lbl_subtitle { color: #3A9EC9; font-size: 13px; }\n"
"    QLabel.field_label { color: #0D6FA6; font-weight: bold; font-size: 13px; }\n"
"    QLineEdit { border: 1px solid #CBD5E0; border-radius: 8px; padding: 8px 12px; background-color: #F7FAFC; color: #2D3748; font-size: 14px; }\n"
"    QLineEdit:focus { border: 1px solid #3182CE; background-color: #FFFFFF; }\n"
"    QComboBox { border: 1px solid #CBD5E0; border-radius: 8px; padding: 8px 12px; background-color: #F7FAFC; font-size: 14px; }\n"
"    QPushButton#btn_register { background-color: #1098F7; color: #FFFFFF; border-radius: 8px; font-weight: bold; font-size: 15px; }\n"
"    QPushButton#btn_register:pressed { background-color: #0d84d1; }\n"
"    QPushButton#btn_back_login { color: #0077C2; font-weight: bold; background: none; border: none; font-size: 13px; }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=RegisterWindow)
        self.centralwidget.setStyleSheet("background-color: #E8F6FD;")
        self.centralwidget.setObjectName("centralwidget")
        self.main_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.main_layout.setContentsMargins(25, 25, 25, 25)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.central_panel = QtWidgets.QFrame(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.central_panel.setFont(font)
        self.central_panel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.central_panel.setObjectName("central_panel")
        self.panel_layout = QtWidgets.QVBoxLayout(self.central_panel)
        self.panel_layout.setContentsMargins(25, 25, 25, 25)
        self.panel_layout.setSpacing(12)
        self.panel_layout.setObjectName("panel_layout")
        self.header_layout = QtWidgets.QVBoxLayout()
        self.header_layout.setSpacing(4)
        self.header_layout.setObjectName("header_layout")
        self.logo_row = QtWidgets.QHBoxLayout()
        self.logo_row.setObjectName("logo_row")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.logo_row.addItem(spacerItem)
        self.lbl_logo_icon = QtWidgets.QLabel(parent=self.central_panel)
        self.lbl_logo_icon.setMinimumSize(QtCore.QSize(76, 76))
        self.lbl_logo_icon.setMaximumSize(QtCore.QSize(76, 76))
        self.lbl_logo_icon.setStyleSheet("background-color: rgb(6, 119, 194);")
        self.lbl_logo_icon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_logo_icon.setObjectName("lbl_logo_icon")
        self.logo_row.addWidget(self.lbl_logo_icon)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.logo_row.addItem(spacerItem1)
        self.header_layout.addLayout(self.logo_row)
        spacerItem2 = QtWidgets.QSpacerItem(0, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.header_layout.addItem(spacerItem2)
        self.lbl_logo = QtWidgets.QLabel(parent=self.central_panel)
        self.lbl_logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_logo.setObjectName("lbl_logo")
        self.header_layout.addWidget(self.lbl_logo)
        self.lbl_subtitle = QtWidgets.QLabel(parent=self.central_panel)
        self.lbl_subtitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_subtitle.setObjectName("lbl_subtitle")
        self.header_layout.addWidget(self.lbl_subtitle)
        self.panel_layout.addLayout(self.header_layout)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.panel_layout.addItem(spacerItem3)
        self.lbl_username_tag = QtWidgets.QLabel(parent=self.central_panel)
        self.lbl_username_tag.setObjectName("lbl_username_tag")
        self.panel_layout.addWidget(self.lbl_username_tag)
        self.txt_username = QtWidgets.QLineEdit(parent=self.central_panel)
        self.txt_username.setStyleSheet(" background-color: #F0FAFF;\n"
"    border: 1.5px solid #B3E0F5;\n"
"    border-radius: 12px;\n"
"    padding: 11px 14px;\n"
"    font-size: 14px;\n"
"    color: #0A3D5C;\n"
"    selection-background-color: #29B6F6;")
        self.txt_username.setObjectName("txt_username")
        self.panel_layout.addWidget(self.txt_username)
        self.lbl_password_tag = QtWidgets.QLabel(parent=self.central_panel)
        self.lbl_password_tag.setObjectName("lbl_password_tag")
        self.panel_layout.addWidget(self.lbl_password_tag)
        self.txt_password = QtWidgets.QLineEdit(parent=self.central_panel)
        self.txt_password.setStyleSheet(" background-color: #F0FAFF;\n"
"    border: 1.5px solid #B3E0F5;\n"
"    border-radius: 12px;\n"
"    padding: 11px 14px;\n"
"    font-size: 14px;\n"
"    color: #0A3D5C;\n"
"    selection-background-color: #29B6F6;")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.txt_password.setObjectName("txt_password")
        self.panel_layout.addWidget(self.txt_password)
        self.lbl_phone_tag = QtWidgets.QLabel(parent=self.central_panel)
        self.lbl_phone_tag.setObjectName("lbl_phone_tag")
        self.panel_layout.addWidget(self.lbl_phone_tag)
        self.txt_phone = QtWidgets.QLineEdit(parent=self.central_panel)
        self.txt_phone.setStyleSheet(" background-color: #F0FAFF;\n"
"    border: 1.5px solid #B3E0F5;\n"
"    border-radius: 12px;\n"
"    padding: 11px 14px;\n"
"    font-size: 14px;\n"
"    color: #0A3D5C;\n"
"    selection-background-color: #29B6F6;")
        self.txt_phone.setObjectName("txt_phone")
        self.panel_layout.addWidget(self.txt_phone)
        self.lbl_role_tag = QtWidgets.QLabel(parent=self.central_panel)
        self.lbl_role_tag.setObjectName("lbl_role_tag")
        self.panel_layout.addWidget(self.lbl_role_tag)
        self.combo_role = QtWidgets.QComboBox(parent=self.central_panel)
        self.combo_role.setStyleSheet(" background-color: #F0FAFF;\n"
"    border: 1.5px solid #B3E0F5;\n"
"    border-radius: 12px;\n"
"    padding: 11px 14px;\n"
"    font-size: 14px;\n"
"    color: #0A3D5C;\n"
"    selection-background-color: #29B6F6;")
        self.combo_role.setObjectName("combo_role")
        self.combo_role.addItem("")
        self.combo_role.addItem("")
        self.panel_layout.addWidget(self.combo_role)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.panel_layout.addItem(spacerItem4)
        self.btn_dangky = QtWidgets.QPushButton(parent=self.central_panel)
        self.btn_dangky.setStyleSheet("background-color: rgb(6, 119, 194);\n"
"    border: 1.5px solid #B3E0F5;\n"
"    border-radius: 12px;\n"
"    padding: 11px 14px;\n"
"    font-size: 14px;\n"
"color: rgb(255, 255, 255);\n"
"    selection-background-color: #29B6F6;")
        self.btn_dangky.setObjectName("btn_dangky")
        self.panel_layout.addWidget(self.btn_dangky)
        self.btn_register = QtWidgets.QPushButton(parent=self.central_panel)
        self.btn_register.setMinimumSize(QtCore.QSize(0, 45))
        self.btn_register.setObjectName("btn_register")
        self.panel_layout.addWidget(self.btn_register)
        self.footer_layout = QtWidgets.QHBoxLayout()
        self.footer_layout.setObjectName("footer_layout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.footer_layout.addItem(spacerItem5)
        self.lbl_hint = QtWidgets.QLabel(parent=self.central_panel)
        self.lbl_hint.setAlignment(QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_hint.setObjectName("lbl_hint")
        self.footer_layout.addWidget(self.lbl_hint)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.footer_layout.addItem(spacerItem6)
        self.btn_back_login = QtWidgets.QPushButton(parent=self.central_panel)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_back_login.setFont(font)
        self.btn_back_login.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_back_login.setObjectName("btn_back_login")
        self.footer_layout.addWidget(self.btn_back_login)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.footer_layout.addItem(spacerItem7)
        self.panel_layout.addLayout(self.footer_layout)
        self.main_layout.addWidget(self.central_panel)
        RegisterWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RegisterWindow)
        QtCore.QMetaObject.connectSlotsByName(RegisterWindow)

    def retranslateUi(self, RegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        RegisterWindow.setWindowTitle(_translate("RegisterWindow", "Metro Ticket System - Đăng ký"))
        self.lbl_logo_icon.setText(_translate("RegisterWindow", "🚇"))
        self.lbl_logo.setText(_translate("RegisterWindow", "Metro Ticket System"))
        self.lbl_subtitle.setText(_translate("RegisterWindow", "Tạo tài khoản mới cho khách hàng"))
        self.lbl_username_tag.setText(_translate("RegisterWindow", "Username"))
        self.lbl_username_tag.setProperty("class", _translate("RegisterWindow", "field_label"))
        self.txt_username.setPlaceholderText(_translate("RegisterWindow", "Nhập tên đăng nhập..."))
        self.lbl_password_tag.setText(_translate("RegisterWindow", "Password"))
        self.lbl_password_tag.setProperty("class", _translate("RegisterWindow", "field_label"))
        self.txt_password.setPlaceholderText(_translate("RegisterWindow", "Nhập mật khẩu an toàn..."))
        self.lbl_phone_tag.setText(_translate("RegisterWindow", "Phone"))
        self.lbl_phone_tag.setProperty("class", _translate("RegisterWindow", "field_label"))
        self.txt_phone.setPlaceholderText(_translate("RegisterWindow", "Nhập số điện thoại (ví dụ: 090...)"))
        self.lbl_role_tag.setText(_translate("RegisterWindow", "Phân quyền (Role)"))
        self.lbl_role_tag.setProperty("class", _translate("RegisterWindow", "field_label"))
        self.combo_role.setItemText(0, _translate("RegisterWindow", "customer"))
        self.combo_role.setItemText(1, _translate("RegisterWindow", "admin"))
        self.btn_dangky.setText(_translate("RegisterWindow", "Đăng ký"))
        self.btn_register.setText(_translate("RegisterWindow", "Đăng ký tài khoản ↗"))
        self.lbl_hint.setText(_translate("RegisterWindow", "Đã có tài khoản?"))
        self.btn_back_login.setText(_translate("RegisterWindow", "Đăng nhập ngay"))
