# Form implementation generated from reading ui file 'D:\Nam1\KTLT\K25411_KTLT\UI_KhachHang\Dangnhap.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(460, 700)
        LoginWindow.setMinimumSize(QtCore.QSize(420, 620))
        LoginWindow.setStyleSheet("\n"
"QWidget#centralwidget {\n"
"    background-color: #E8F6FD;\n"
"}\n"
"QFrame#card {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 20px;\n"
"    border: 1.5px solid #B3E0F5;\n"
"}\n"
"QLabel#lbl_title {\n"
"    color: #0A4D7A;\n"
"    font-size: 22px;\n"
"    font-weight: 700;\n"
"}\n"
"QLabel#lbl_subtitle {\n"
"    color: #3A9EC9;\n"
"    font-size: 13px;\n"
"}\n"
"QLabel#lbl_field_user,\n"
"QLabel#lbl_field_pass {\n"
"    color: #0D6FA6;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"}\n"
"QLineEdit#inp_username,\n"
"QLineEdit#inp_password {\n"
"    background-color: #F0FAFF;\n"
"    border: 1.5px solid #B3E0F5;\n"
"    border-radius: 12px;\n"
"    padding: 11px 14px;\n"
"    font-size: 14px;\n"
"    color: #0A3D5C;\n"
"    selection-background-color: #29B6F6;\n"
"}\n"
"QLineEdit#inp_username:hover,\n"
"QLineEdit#inp_password:hover {\n"
"    border-color: #29B6F6;\n"
"    background-color: #E8F6FD;\n"
"}\n"
"QLineEdit#inp_username:focus,\n"
"QLineEdit#inp_password:focus {\n"
"    border-color: #0288D1;\n"
"    background-color: #FFFFFF;\n"
"}\n"
"QPushButton#btn_eye {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #4FC3F7;\n"
"    font-size: 16px;\n"
"    padding: 0px;\n"
"}\n"
"QPushButton#btn_eye:hover {\n"
"    color: #0288D1;\n"
"}\n"
"QPushButton#btn_login {\n"
"    background: qlineargradient(x1:0,y1:0,x2:1,y2:0,\n"
"        stop:0 #0288D1, stop:1 #29B6F6);\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 14px;\n"
"    font-size: 15px;\n"
"    font-weight: 700;\n"
"    padding: 14px 0px;\n"
"}\n"
"QPushButton#btn_login:hover {\n"
"    background: qlineargradient(x1:0,y1:0,x2:1,y2:0,\n"
"        stop:0 #039BE5, stop:1 #4FC3F7);\n"
"}\n"
"QPushButton#btn_login:pressed {\n"
"    background: qlineargradient(x1:0,y1:0,x2:1,y2:0,\n"
"        stop:0 #0277BD, stop:1 #0288D1);\n"
"}\n"
"QPushButton#btn_login:disabled {\n"
"    background: #B3E0F5;\n"
"    color: #FFFFFF;\n"
"}\n"
"QPushButton#btn_register,\n"
"QPushButton#btn_forgot {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #0288D1;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"    text-decoration: underline;\n"
"    padding: 0px;\n"
"}\n"
"QPushButton#btn_register:hover,\n"
"QPushButton#btn_forgot:hover {\n"
"    color: #01579B;\n"
"}\n"
"QFrame#banner {\n"
"    background-color: #E1F5FE;\n"
"    border-radius: 12px;\n"
"    border: 1px solid #B3E0F5;\n"
"}\n"
"QLabel#lbl_banner {\n"
"    color: #0D6FA6;\n"
"    font-size: 12px;\n"
"}\n"
"QLabel#lbl_divider {\n"
"    color: #81D4FA;\n"
"    font-size: 12px;\n"
"}\n"
"QFrame#line_left,\n"
"QFrame#line_right {\n"
"    color: #B3E0F5;\n"
"}\n"
"QLabel#lbl_no_account {\n"
"    color: #3A9EC9;\n"
"    font-size: 13px;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=LoginWindow)
        self.centralwidget.setGeometry(QtCore.QRect(0, 0, 460, 700))
        self.centralwidget.setObjectName("centralwidget")
        self.root_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.root_layout.setContentsMargins(40, 40, 40, 32)
        self.root_layout.setSpacing(0)
        self.root_layout.setObjectName("root_layout")
        self.logo_row = QtWidgets.QHBoxLayout()
        self.logo_row.setObjectName("logo_row")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.logo_row.addItem(spacerItem)
        self.lbl_logo = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_logo.setMinimumSize(QtCore.QSize(76, 76))
        self.lbl_logo.setMaximumSize(QtCore.QSize(76, 76))
        self.lbl_logo.setStyleSheet("\n"
"QLabel#lbl_logo {\n"
"    background-color: #0288D1;\n"
"    border-radius: 38px;\n"
"    font-size: 30px;\n"
"    border: 2px solid #29B6F6;\n"
"}\n"
"        ")
        self.lbl_logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_logo.setObjectName("lbl_logo")
        self.logo_row.addWidget(self.lbl_logo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.logo_row.addItem(spacerItem1)
        self.root_layout.addLayout(self.logo_row)
        spacerItem2 = QtWidgets.QSpacerItem(0, 12, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.root_layout.addItem(spacerItem2)
        self.lbl_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.root_layout.addWidget(self.lbl_title)
        spacerItem3 = QtWidgets.QSpacerItem(0, 4, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.root_layout.addItem(spacerItem3)
        self.lbl_subtitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_subtitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_subtitle.setObjectName("lbl_subtitle")
        self.root_layout.addWidget(self.lbl_subtitle)
        spacerItem4 = QtWidgets.QSpacerItem(0, 24, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.root_layout.addItem(spacerItem4)
        self.card = QtWidgets.QFrame(parent=self.centralwidget)
        self.card.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.card.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.card.setObjectName("card")
        self.card_layout = QtWidgets.QVBoxLayout(self.card)
        self.card_layout.setContentsMargins(28, 28, 28, 24)
        self.card_layout.setSpacing(0)
        self.card_layout.setObjectName("card_layout")
        self.lbl_field_user = QtWidgets.QLabel(parent=self.card)
        self.lbl_field_user.setObjectName("lbl_field_user")
        self.card_layout.addWidget(self.lbl_field_user)
        spacerItem5 = QtWidgets.QSpacerItem(0, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.card_layout.addItem(spacerItem5)
        self.inp_username = QtWidgets.QLineEdit(parent=self.card)
        self.inp_username.setClearButtonEnabled(True)
        self.inp_username.setObjectName("inp_username")
        self.card_layout.addWidget(self.inp_username)
        spacerItem6 = QtWidgets.QSpacerItem(0, 16, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.card_layout.addItem(spacerItem6)
        self.lbl_field_pass = QtWidgets.QLabel(parent=self.card)
        self.lbl_field_pass.setObjectName("lbl_field_pass")
        self.card_layout.addWidget(self.lbl_field_pass)
        spacerItem7 = QtWidgets.QSpacerItem(0, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.card_layout.addItem(spacerItem7)
        self.pass_row = QtWidgets.QHBoxLayout()
        self.pass_row.setSpacing(0)
        self.pass_row.setObjectName("pass_row")
        self.inp_password = QtWidgets.QLineEdit(parent=self.card)
        self.inp_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.inp_password.setObjectName("inp_password")
        self.pass_row.addWidget(self.inp_password)
        self.btn_eye = QtWidgets.QPushButton(parent=self.card)
        self.btn_eye.setMinimumSize(QtCore.QSize(40, 48))
        self.btn_eye.setMaximumSize(QtCore.QSize(40, 48))
        self.btn_eye.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_eye.setFlat(True)
        self.btn_eye.setObjectName("btn_eye")
        self.pass_row.addWidget(self.btn_eye)
        self.card_layout.addLayout(self.pass_row)
        spacerItem8 = QtWidgets.QSpacerItem(0, 22, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.card_layout.addItem(spacerItem8)
        self.btn_login = QtWidgets.QPushButton(parent=self.card)
        self.btn_login.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_login.setDefault(True)
        self.btn_login.setObjectName("btn_login")
        self.card_layout.addWidget(self.btn_login)
        spacerItem9 = QtWidgets.QSpacerItem(0, 18, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.card_layout.addItem(spacerItem9)
        self.divider_row = QtWidgets.QHBoxLayout()
        self.divider_row.setSpacing(8)
        self.divider_row.setObjectName("divider_row")
        self.line_left = QtWidgets.QFrame(parent=self.card)
        self.line_left.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_left.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_left.setObjectName("line_left")
        self.divider_row.addWidget(self.line_left)
        self.lbl_divider = QtWidgets.QLabel(parent=self.card)
        self.lbl_divider.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_divider.setObjectName("lbl_divider")
        self.divider_row.addWidget(self.lbl_divider)
        self.line_right = QtWidgets.QFrame(parent=self.card)
        self.line_right.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_right.setObjectName("line_right")
        self.divider_row.addWidget(self.line_right)
        self.card_layout.addLayout(self.divider_row)
        spacerItem10 = QtWidgets.QSpacerItem(0, 14, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.card_layout.addItem(spacerItem10)
        self.register_row = QtWidgets.QHBoxLayout()
        self.register_row.setObjectName("register_row")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.register_row.addItem(spacerItem11)
        self.lbl_no_account = QtWidgets.QLabel(parent=self.card)
        self.lbl_no_account.setObjectName("lbl_no_account")
        self.register_row.addWidget(self.lbl_no_account)
        spacerItem12 = QtWidgets.QSpacerItem(4, 0, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.register_row.addItem(spacerItem12)
        self.btn_register = QtWidgets.QPushButton(parent=self.card)
        self.btn_register.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_register.setFlat(True)
        self.btn_register.setObjectName("btn_register")
        self.register_row.addWidget(self.btn_register)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.register_row.addItem(spacerItem13)
        self.card_layout.addLayout(self.register_row)
        spacerItem14 = QtWidgets.QSpacerItem(0, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.card_layout.addItem(spacerItem14)
        self.forgot_row = QtWidgets.QHBoxLayout()
        self.forgot_row.setObjectName("forgot_row")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.forgot_row.addItem(spacerItem15)
        self.btn_forgot = QtWidgets.QPushButton(parent=self.card)
        self.btn_forgot.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_forgot.setFlat(True)
        self.btn_forgot.setObjectName("btn_forgot")
        self.forgot_row.addWidget(self.btn_forgot)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.forgot_row.addItem(spacerItem16)
        self.card_layout.addLayout(self.forgot_row)
        self.root_layout.addWidget(self.card)
        spacerItem17 = QtWidgets.QSpacerItem(0, 16, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.root_layout.addItem(spacerItem17)
        self.banner = QtWidgets.QFrame(parent=self.centralwidget)
        self.banner.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.banner.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.banner.setObjectName("banner")
        self.banner_layout = QtWidgets.QHBoxLayout(self.banner)
        self.banner_layout.setContentsMargins(14, 11, 14, 11)
        self.banner_layout.setSpacing(8)
        self.banner_layout.setObjectName("banner_layout")
        self.lbl_banner_icon = QtWidgets.QLabel(parent=self.banner)
        self.lbl_banner_icon.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.lbl_banner_icon.setObjectName("lbl_banner_icon")
        self.banner_layout.addWidget(self.lbl_banner_icon)
        self.lbl_banner = QtWidgets.QLabel(parent=self.banner)
        self.lbl_banner.setWordWrap(True)
        self.lbl_banner.setObjectName("lbl_banner")
        self.banner_layout.addWidget(self.lbl_banner)
        self.root_layout.addWidget(self.banner)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.root_layout.addItem(spacerItem18)
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)
        LoginWindow.setTabOrder(self.inp_username, self.inp_password)
        LoginWindow.setTabOrder(self.inp_password, self.btn_eye)
        LoginWindow.setTabOrder(self.btn_eye, self.btn_login)
        LoginWindow.setTabOrder(self.btn_login, self.btn_register)
        LoginWindow.setTabOrder(self.btn_register, self.btn_forgot)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Metro Ticket System"))
        self.lbl_logo.setText(_translate("LoginWindow", "🚇"))
        self.lbl_title.setText(_translate("LoginWindow", "Metro Ticket System"))
        self.lbl_subtitle.setText(_translate("LoginWindow", "Hệ thống quản lý bán vé metro"))
        self.lbl_field_user.setText(_translate("LoginWindow", "Username"))
        self.inp_username.setPlaceholderText(_translate("LoginWindow", "Nhập username của bạn"))
        self.lbl_field_pass.setText(_translate("LoginWindow", "Password"))
        self.inp_password.setPlaceholderText(_translate("LoginWindow", "Nhập mật khẩu"))
        self.btn_eye.setText(_translate("LoginWindow", "👁"))
        self.btn_login.setText(_translate("LoginWindow", "Đăng nhập  ↗"))
        self.lbl_divider.setText(_translate("LoginWindow", "hoặc"))
        self.lbl_no_account.setText(_translate("LoginWindow", "Chưa có tài khoản?"))
        self.btn_register.setText(_translate("LoginWindow", "Đăng ký ngay"))
        self.btn_forgot.setText(_translate("LoginWindow", "Quên mật khẩu?"))
        self.lbl_banner_icon.setText(_translate("LoginWindow", "ℹ️"))
        self.lbl_banner.setText(_translate("LoginWindow", "<b>Phân quyền:</b> Hệ thống tự động nhận diện role (admin/customer) sau khi đăng nhập."))
