# Form implementation generated from reading ui file 'Dangky_Ver2.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegisterWindow_Ver2(object):
    def setupUi(self, RegisterWindow):
        RegisterWindow.setObjectName("RegisterWindow")
        RegisterWindow.resize(460, 760)
        RegisterWindow.setMinimumSize(QtCore.QSize(420, 680))
        RegisterWindow.setStyleSheet("\n"
"/* ── Nền tổng: gradient xanh đậm theo chiều dọc, đồng bộ màn đăng nhập ── */\n"
"QWidget#centralwidget {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0.3, y2:1,\n"
"        stop:0 #0D1F3C,\n"
"        stop:0.4 #0A3060,\n"
"        stop:0.7 #0D4080,\n"
"        stop:1   #1A5FA8);\n"
"}\n"
"\n"
"/* ── Card đăng ký nổi lên ── */\n"
"QFrame#central_panel {\n"
"    background-color: rgba(255, 255, 255, 0.97);\n"
"    border-radius: 24px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.15);\n"
"}\n"
"\n"
"/* ── Logo: khung ngoài tạo hiệu ứng 3D ── */\n"
"QFrame#logo_outer {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #1E90FF, stop:0.5 #0060D0, stop:1 #003A8C);\n"
"    border-radius: 22px;\n"
"    border-top: 2px solid rgba(255,255,255,0.28);\n"
"    border-left: 1px solid rgba(255,255,255,0.12);\n"
"    border-right: 1px solid rgba(0,0,0,0.25);\n"
"    border-bottom: 2px solid rgba(0,0,0,0.35);\n"
"}\n"
"QFrame#logo_inner {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #2AA0FF, stop:1 #0070E0);\n"
"    border-radius: 14px;\n"
"    border-top: 1px solid rgba(255,255,255,0.2);\n"
"    border-bottom: 1px solid rgba(0,0,0,0.3);\n"
"}\n"
"QLabel#lbl_logo_icon {\n"
"    color: #E0F2FE;\n"
"    font-size: 26px;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* ── Tiêu đề ── */\n"
"QLabel#lbl_logo {\n"
"    color: #0A3D62;\n"
"    font-size: 21px;\n"
"    font-weight: 700;\n"
"    background: transparent;\n"
"}\n"
"QLabel#lbl_subtitle {\n"
"    color: rgba(148, 213, 252, 0.85);\n"
"    font-size: 12px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* ── Label field ── */\n"
"QLabel#lbl_username_tag,\n"
"QLabel#lbl_password_tag,\n"
"QLabel#lbl_phone_tag,\n"
"QLabel#lbl_dob_tag {\n"
"    color: #0369A1;\n"
"    font-size: 11px;\n"
"    font-weight: 700;\n"
"    letter-spacing: 0.8px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* ── Input fields ── */\n"
"QLineEdit#txt_username,\n"
"QLineEdit#txt_password,\n"
"QLineEdit#txt_phone,\n"
"QDateEdit#DoB {\n"
"    background-color: #F0F9FF;\n"
"    border: 1.5px solid #BAE6FD;\n"
"    border-radius: 12px;\n"
"    padding: 11px 14px;\n"
"    font-size: 14px;\n"
"    color: #0C4A6E;\n"
"    selection-background-color: #29B6F6;\n"
"}\n"
"QLineEdit#txt_username:hover,\n"
"QLineEdit#txt_password:hover,\n"
"QLineEdit#txt_phone:hover,\n"
"QDateEdit#DoB:hover {\n"
"    border-color: #38BDF8;\n"
"    background-color: #E8F6FD;\n"
"}\n"
"QLineEdit#txt_username:focus,\n"
"QLineEdit#txt_password:focus,\n"
"QLineEdit#txt_phone:focus,\n"
"QDateEdit#DoB:focus {\n"
"    border-color: #0284C7;\n"
"    background-color: #FFFFFF;\n"
"}\n"
"QDateEdit#DoB::drop-down {\n"
"    border: none;\n"
"    width: 24px;\n"
"}\n"
"\n"
"/* ── Nút đăng ký gradient 3D ── */\n"
"QPushButton#btn_dangky {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #0284C7, stop:0.5 #0EA5E9, stop:1 #38BDF8);\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 14px;\n"
"    font-size: 15px;\n"
"    font-weight: 700;\n"
"    padding: 14px 0px;\n"
"    border-top: 1px solid rgba(255,255,255,0.2);\n"
"}\n"
"QPushButton#btn_dangky:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #0369A1, stop:0.5 #0284C7, stop:1 #0EA5E9);\n"
"}\n"
"QPushButton#btn_dangky:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #075985, stop:1 #0284C7);\n"
"    border-top: 1px solid rgba(0,0,0,0.15);\n"
"}\n"
"QPushButton#btn_dangky:disabled {\n"
"    background: #BAE6FD;\n"
"    color: rgba(255,255,255,0.6);\n"
"}\n"
"\n"
"/* ── Link buttons ── */\n"
"QPushButton#btn_back_login {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #0284C7;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"    text-decoration: underline;\n"
"    padding: 0px;\n"
"}\n"
"QPushButton#btn_back_login:hover { color: #075985; }\n"
"\n"
"QLabel#lbl_hint { color: #64748B; font-size: 13px; background: transparent; }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=RegisterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.root_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.root_layout.setContentsMargins(32, 32, 32, 28)
        self.root_layout.setSpacing(0)
        self.root_layout.setObjectName("root_layout")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.root_layout.addItem(spacerItem)
        self.central_panel = QtWidgets.QFrame(parent=self.centralwidget)
        self.central_panel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.central_panel.setObjectName("central_panel")
        self.panel_layout = QtWidgets.QVBoxLayout(self.central_panel)
        self.panel_layout.setContentsMargins(28, 26, 28, 24)
        self.panel_layout.setSpacing(0)
        self.panel_layout.setObjectName("panel_layout")
        self.logo_row = QtWidgets.QHBoxLayout()
        self.logo_row.setObjectName("logo_row")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.logo_row.addItem(spacerItem1)
        self.logo_outer = QtWidgets.QFrame(parent=self.central_panel)
        self.logo_outer.setMinimumSize(QtCore.QSize(76, 76))
        self.logo_outer.setMaximumSize(QtCore.QSize(76, 76))
        self.logo_outer.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.logo_outer.setObjectName("logo_outer")
        self.logo_outer_layout = QtWidgets.QVBoxLayout(self.logo_outer)
        self.logo_outer_layout.setContentsMargins(9, 9, 9, 9)
        self.logo_outer_layout.setObjectName("logo_outer_layout")
        self.logo_inner = QtWidgets.QFrame(parent=self.logo_outer)
        self.logo_inner.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.logo_inner.setObjectName("logo_inner")
        self.logo_inner_layout = QtWidgets.QVBoxLayout(self.logo_inner)
        self.logo_inner_layout.setContentsMargins(0, 0, 0, 0)
        self.logo_inner_layout.setObjectName("logo_inner_layout")
        self.lbl_logo_icon = QtWidgets.QLabel(parent=self.logo_inner)
        self.lbl_logo_icon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_logo_icon.setObjectName("lbl_logo_icon")
        self.logo_inner_layout.addWidget(self.lbl_logo_icon)
        self.logo_outer_layout.addWidget(self.logo_inner)
        self.logo_row.addWidget(self.logo_outer)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.logo_row.addItem(spacerItem2)
        self.panel_layout.addLayout(self.logo_row)
        spacerItem3 = QtWidgets.QSpacerItem(0, 14, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.panel_layout.addItem(spacerItem3)
        self.lbl_logo = QtWidgets.QLabel(parent=self.central_panel)
        self.lbl_logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_logo.setObjectName("lbl_logo")
        self.panel_layout.addWidget(self.lbl_logo)
        spacerItem4 = QtWidgets.QSpacerItem(0, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.panel_layout.addItem(spacerItem4)
        self.lbl_subtitle = QtWidgets.QLabel(parent=self.central_panel)
        self.lbl_subtitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_subtitle.setObjectName("lbl_subtitle")
        self.panel_layout.addWidget(self.lbl_subtitle)
        spacerItem5 = QtWidgets.QSpacerItem(0, 22, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.panel_layout.addItem(spacerItem5)
        self.lbl_username_tag = QtWidgets.QLabel(parent=self.central_panel)
        self.lbl_username_tag.setObjectName("lbl_username_tag")
        self.panel_layout.addWidget(self.lbl_username_tag)
        spacerItem6 = QtWidgets.QSpacerItem(0, 7, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.panel_layout.addItem(spacerItem6)
        self.txt_username = QtWidgets.QLineEdit(parent=self.central_panel)
        self.txt_username.setClearButtonEnabled(True)
        self.txt_username.setObjectName("txt_username")
        self.panel_layout.addWidget(self.txt_username)
        spacerItem7 = QtWidgets.QSpacerItem(0, 16, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.panel_layout.addItem(spacerItem7)
        self.lbl_password_tag = QtWidgets.QLabel(parent=self.central_panel)
        self.lbl_password_tag.setObjectName("lbl_password_tag")
        self.panel_layout.addWidget(self.lbl_password_tag)
        spacerItem8 = QtWidgets.QSpacerItem(0, 7, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.panel_layout.addItem(spacerItem8)
        self.txt_password = QtWidgets.QLineEdit(parent=self.central_panel)
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_password.setObjectName("txt_password")
        self.panel_layout.addWidget(self.txt_password)
        spacerItem9 = QtWidgets.QSpacerItem(0, 16, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.panel_layout.addItem(spacerItem9)
        self.lbl_phone_tag = QtWidgets.QLabel(parent=self.central_panel)
        self.lbl_phone_tag.setObjectName("lbl_phone_tag")
        self.panel_layout.addWidget(self.lbl_phone_tag)
        spacerItem10 = QtWidgets.QSpacerItem(0, 7, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.panel_layout.addItem(spacerItem10)
        self.txt_phone = QtWidgets.QLineEdit(parent=self.central_panel)
        self.txt_phone.setObjectName("txt_phone")
        self.panel_layout.addWidget(self.txt_phone)
        spacerItem11 = QtWidgets.QSpacerItem(0, 16, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.panel_layout.addItem(spacerItem11)
        self.lbl_dob_tag = QtWidgets.QLabel(parent=self.central_panel)
        self.lbl_dob_tag.setObjectName("lbl_dob_tag")
        self.panel_layout.addWidget(self.lbl_dob_tag)
        spacerItem12 = QtWidgets.QSpacerItem(0, 7, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.panel_layout.addItem(spacerItem12)
        self.DoB = QtWidgets.QDateEdit(parent=self.central_panel)
        self.DoB.setCalendarPopup(True)
        self.DoB.setObjectName("DoB")
        self.panel_layout.addWidget(self.DoB)
        spacerItem13 = QtWidgets.QSpacerItem(0, 24, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.panel_layout.addItem(spacerItem13)
        self.btn_dangky = QtWidgets.QPushButton(parent=self.central_panel)
        self.btn_dangky.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_dangky.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_dangky.setDefault(True)
        self.btn_dangky.setObjectName("btn_dangky")
        self.panel_layout.addWidget(self.btn_dangky)
        self.btn_register = QtWidgets.QPushButton(parent=self.central_panel)
        self.btn_register.setVisible(False)
        self.btn_register.setMaximumSize(QtCore.QSize(0, 0))
        self.btn_register.setObjectName("btn_register")
        self.panel_layout.addWidget(self.btn_register)
        spacerItem14 = QtWidgets.QSpacerItem(0, 18, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.panel_layout.addItem(spacerItem14)
        self.footer_layout = QtWidgets.QHBoxLayout()
        self.footer_layout.setObjectName("footer_layout")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.footer_layout.addItem(spacerItem15)
        self.lbl_hint = QtWidgets.QLabel(parent=self.central_panel)
        self.lbl_hint.setObjectName("lbl_hint")
        self.footer_layout.addWidget(self.lbl_hint)
        spacerItem16 = QtWidgets.QSpacerItem(4, 0, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.footer_layout.addItem(spacerItem16)
        self.btn_back_login = QtWidgets.QPushButton(parent=self.central_panel)
        self.btn_back_login.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_back_login.setFlat(True)
        self.btn_back_login.setObjectName("btn_back_login")
        self.footer_layout.addWidget(self.btn_back_login)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.footer_layout.addItem(spacerItem17)
        self.panel_layout.addLayout(self.footer_layout)
        self.root_layout.addWidget(self.central_panel)
        spacerItem18 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.root_layout.addItem(spacerItem18)
        RegisterWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RegisterWindow)
        QtCore.QMetaObject.connectSlotsByName(RegisterWindow)
        RegisterWindow.setTabOrder(self.txt_username, self.txt_password)
        RegisterWindow.setTabOrder(self.txt_password, self.txt_phone)
        RegisterWindow.setTabOrder(self.txt_phone, self.DoB)
        RegisterWindow.setTabOrder(self.DoB, self.btn_dangky)
        RegisterWindow.setTabOrder(self.btn_dangky, self.btn_back_login)

    def retranslateUi(self, RegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        RegisterWindow.setWindowTitle(_translate("RegisterWindow", "Metro Ticket System - Đăng ký"))
        self.lbl_logo_icon.setText(_translate("RegisterWindow", "🚇"))
        self.lbl_logo.setText(_translate("RegisterWindow", "Metro Ticket System"))
        self.lbl_subtitle.setText(_translate("RegisterWindow", "Tạo tài khoản mới cho khách hàng"))
        self.lbl_username_tag.setText(_translate("RegisterWindow", "USERNAME"))
        self.txt_username.setPlaceholderText(_translate("RegisterWindow", "Nhập tên đăng nhập..."))
        self.lbl_password_tag.setText(_translate("RegisterWindow", "PASSWORD"))
        self.txt_password.setPlaceholderText(_translate("RegisterWindow", "Nhập mật khẩu an toàn..."))
        self.lbl_phone_tag.setText(_translate("RegisterWindow", "PHONE"))
        self.txt_phone.setPlaceholderText(_translate("RegisterWindow", "Nhập số điện thoại (ví dụ: 090...)"))
        self.lbl_dob_tag.setText(_translate("RegisterWindow", "DATE OF BIRTH"))
        self.btn_dangky.setText(_translate("RegisterWindow", "Đăng ký tài khoản  ↗"))
        self.btn_register.setText(_translate("RegisterWindow", "Đăng ký tài khoản ↗"))
        self.lbl_hint.setText(_translate("RegisterWindow", "Đã có tài khoản?"))
        self.btn_back_login.setText(_translate("RegisterWindow", "Đăng nhập ngay"))
