# Form implementation generated from reading ui file 'Hoanve.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RefundWindow(object):
    def setupUi(self, RefundWindow):
        RefundWindow.setObjectName("RefundWindow")
        RefundWindow.resize(460, 750)
        RefundWindow.setMinimumSize(QtCore.QSize(420, 680))
        RefundWindow.setStyleSheet("\n"
"/* ── Nền tổng: đồng bộ với NapTien / Dashboard ── */\n"
"QWidget#centralwidget {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0.3, y2:1,\n"
"        stop:0 #0D1F3C,\n"
"        stop:0.4 #0A3060,\n"
"        stop:0.7 #0D4080,\n"
"        stop:1   #1A5FA8);\n"
"}\n"
"\n"
"/* ── Header ── */\n"
"QPushButton#btn_back {\n"
"    background: rgba(255,255,255,0.10);\n"
"    border: 1px solid rgba(255,255,255,0.18);\n"
"    border-radius: 10px;\n"
"    color: #E0F2FE;\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    padding: 6px 14px;\n"
"}\n"
"QPushButton#btn_back:hover { background: rgba(255,255,255,0.18); }\n"
"\n"
"QLabel#lbl_header_title {\n"
"    color: #FFFFFF;\n"
"    font-size: 17px;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"/* ── Card số dư (đồng bộ dashboard) ── */\n"
"QFrame#balance_card {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #0EA5E9, stop:0.5 #0284C7, stop:1 #075985);\n"
"    border-radius: 20px;\n"
"    border-top: 1px solid rgba(255,255,255,0.25);\n"
"}\n"
"QLabel#lbl_balance_caption {\n"
"    color: rgba(255,255,255,0.85);\n"
"    font-size: 11px;\n"
"    font-weight: 700;\n"
"    letter-spacing: 1px;\n"
"}\n"
"QLabel#lbl_balance_value {\n"
"    color: #FFFFFF;\n"
"    font-size: 30px;\n"
"    font-weight: 800;\n"
"}\n"
"\n"
"/* ── Card trắng chứa nội dung ── */\n"
"QFrame#refund_card {\n"
"    background-color: rgba(255, 255, 255, 0.97);\n"
"    border-radius: 22px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.15);\n"
"}\n"
"\n"
"/* ── Label nhãn field ── */\n"
"QLabel#lbl_field_ticket,\n"
"QLabel#lbl_field_info {\n"
"    color: #0369A1;\n"
"    font-size: 11px;\n"
"    font-weight: 700;\n"
"    letter-spacing: 0.8px;\n"
"}\n"
"\n"
"/* ── Ô nhập mã vé ── */\n"
"QLineEdit#inp_ticket_code {\n"
"    background-color: #F0F9FF;\n"
"    border: 1.5px solid #BAE6FD;\n"
"    border-radius: 12px;\n"
"    padding: 12px 14px;\n"
"    font-size: 15px;\n"
"    font-weight: 600;\n"
"    color: #0C4A6E;\n"
"    selection-background-color: #29B6F6;\n"
"}\n"
"QLineEdit#inp_ticket_code:hover { border-color: #38BDF8; background-color: #E8F6FD; }\n"
"QLineEdit#inp_ticket_code:focus { border-color: #0284C7; background-color: #FFFFFF; }\n"
"\n"
"/* ── Nút tra cứu ── */\n"
"QPushButton#btn_lookup {\n"
"    background: rgba(14,165,233,0.12);\n"
"    border: 1.5px solid #BAE6FD;\n"
"    border-radius: 12px;\n"
"    color: #0284C7;\n"
"    font-size: 13px;\n"
"    font-weight: 700;\n"
"    padding: 12px 0px;\n"
"}\n"
"QPushButton#btn_lookup:hover {\n"
"    background: rgba(14,165,233,0.22);\n"
"    border-color: #0EA5E9;\n"
"}\n"
"\n"
"/* ── Card thông tin vé (hiện ra sau khi tra cứu) ── */\n"
"QFrame#ticket_info_card {\n"
"    background-color: #F0F9FF;\n"
"    border: 1.5px solid #BAE6FD;\n"
"    border-radius: 14px;\n"
"}\n"
"QLabel#lbl_ticket_route {\n"
"    color: #0C4A6E;\n"
"    font-size: 14px;\n"
"    font-weight: 700;\n"
"}\n"
"QLabel#lbl_ticket_type {\n"
"    color: #0284C7;\n"
"    font-size: 12px;\n"
"    font-weight: 600;\n"
"}\n"
"QLabel#lbl_ticket_date {\n"
"    color: #64748B;\n"
"    font-size: 11px;\n"
"}\n"
"QLabel#lbl_ticket_price_caption {\n"
"    color: #64748B;\n"
"    font-size: 11px;\n"
"}\n"
"QLabel#lbl_ticket_price_value {\n"
"    color: #0EA5E9;\n"
"    font-size: 20px;\n"
"    font-weight: 800;\n"
"}\n"
"\n"
"/* ── Badge trạng thái vé ── */\n"
"QLabel#badge_status {\n"
"    background-color: #DCFCE7;\n"
"    color: #166534;\n"
"    border-radius: 8px;\n"
"    font-size: 11px;\n"
"    font-weight: 700;\n"
"    padding: 3px 10px;\n"
"}\n"
"\n"
"/* ── Divider ── */\n"
"QFrame#divider {\n"
"    color: #E0F2FE;\n"
"}\n"
"\n"
"/* ── Số tiền hoàn (hiển thị nổi bật) ── */\n"
"QFrame#refund_amount_row {\n"
"    background-color: #FFF7ED;\n"
"    border: 1.5px solid #FED7AA;\n"
"    border-radius: 12px;\n"
"}\n"
"QLabel#lbl_refund_caption {\n"
"    color: #9A3412;\n"
"    font-size: 11px;\n"
"    font-weight: 700;\n"
"    letter-spacing: 0.6px;\n"
"}\n"
"QLabel#lbl_refund_amount {\n"
"    color: #EA580C;\n"
"    font-size: 22px;\n"
"    font-weight: 800;\n"
"}\n"
"QLabel#lbl_refund_note {\n"
"    color: #C2410C;\n"
"    font-size: 11px;\n"
"}\n"
"\n"
"/* ── Nút xác nhận hoàn vé ── */\n"
"QPushButton#btn_confirm_refund {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #0284C7, stop:0.5 #0EA5E9, stop:1 #38BDF8);\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 14px;\n"
"    font-size: 15px;\n"
"    font-weight: 700;\n"
"    padding: 14px 0px;\n"
"    border-top: 1px solid rgba(255,255,255,0.2);\n"
"}\n"
"QPushButton#btn_confirm_refund:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #0369A1, stop:0.5 #0284C7, stop:1 #0EA5E9);\n"
"}\n"
"QPushButton#btn_confirm_refund:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #075985, stop:1 #0284C7);\n"
"}\n"
"QPushButton#btn_confirm_refund:disabled {\n"
"    background: #BAE6FD;\n"
"    color: rgba(255,255,255,0.6);\n"
"}\n"
"\n"
"QLabel#lbl_bottom_note {\n"
"    color: rgba(255,255,255,0.55);\n"
"    font-size: 11px;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=RefundWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.root_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.root_layout.setContentsMargins(28, 24, 28, 28)
        self.root_layout.setSpacing(0)
        self.root_layout.setObjectName("root_layout")
        self.header_row = QtWidgets.QHBoxLayout()
        self.header_row.setSpacing(0)
        self.header_row.setObjectName("header_row")
        self.btn_back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_back.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_back.setFlat(True)
        self.btn_back.setObjectName("btn_back")
        self.header_row.addWidget(self.btn_back)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.header_row.addItem(spacerItem)
        self.lbl_header_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_header_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_header_title.setObjectName("lbl_header_title")
        self.header_row.addWidget(self.lbl_header_title)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.header_row.addItem(spacerItem1)
        self.root_layout.addLayout(self.header_row)
        spacerItem2 = QtWidgets.QSpacerItem(0, 18, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.root_layout.addItem(spacerItem2)
        self.balance_card = QtWidgets.QFrame(parent=self.centralwidget)
        self.balance_card.setMinimumSize(QtCore.QSize(0, 88))
        self.balance_card.setMaximumSize(QtCore.QSize(16777215, 88))
        self.balance_card.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.balance_card.setObjectName("balance_card")
        self.balance_card_layout = QtWidgets.QVBoxLayout(self.balance_card)
        self.balance_card_layout.setContentsMargins(20, 14, 20, 14)
        self.balance_card_layout.setSpacing(4)
        self.balance_card_layout.setObjectName("balance_card_layout")
        self.lbl_balance_caption = QtWidgets.QLabel(parent=self.balance_card)
        self.lbl_balance_caption.setObjectName("lbl_balance_caption")
        self.balance_card_layout.addWidget(self.lbl_balance_caption)
        self.lbl_balance_value = QtWidgets.QLabel(parent=self.balance_card)
        self.lbl_balance_value.setObjectName("lbl_balance_value")
        self.balance_card_layout.addWidget(self.lbl_balance_value)
        self.root_layout.addWidget(self.balance_card)
        spacerItem3 = QtWidgets.QSpacerItem(0, 16, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.root_layout.addItem(spacerItem3)
        self.refund_card = QtWidgets.QFrame(parent=self.centralwidget)
        self.refund_card.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.refund_card.setObjectName("refund_card")
        self.refund_card_layout = QtWidgets.QVBoxLayout(self.refund_card)
        self.refund_card_layout.setContentsMargins(22, 22, 22, 22)
        self.refund_card_layout.setSpacing(14)
        self.refund_card_layout.setObjectName("refund_card_layout")
        self.lbl_field_ticket = QtWidgets.QLabel(parent=self.refund_card)
        self.lbl_field_ticket.setObjectName("lbl_field_ticket")
        self.refund_card_layout.addWidget(self.lbl_field_ticket)
        self.lookup_row = QtWidgets.QHBoxLayout()
        self.lookup_row.setSpacing(10)
        self.lookup_row.setObjectName("lookup_row")
        self.inp_ticket_code = QtWidgets.QLineEdit(parent=self.refund_card)
        self.inp_ticket_code.setMinimumHeight(46)
        self.inp_ticket_code.setObjectName("inp_ticket_code")
        self.lookup_row.addWidget(self.inp_ticket_code)
        self.btn_lookup = QtWidgets.QPushButton(parent=self.refund_card)
        self.btn_lookup.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_lookup.setMinimumSize(QtCore.QSize(88, 46))
        self.btn_lookup.setMaximumSize(QtCore.QSize(88, 46))
        self.btn_lookup.setObjectName("btn_lookup")
        self.lookup_row.addWidget(self.btn_lookup)
        self.refund_card_layout.addLayout(self.lookup_row)
        self.divider = QtWidgets.QFrame(parent=self.refund_card)
        self.divider.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.divider.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.divider.setObjectName("divider")
        self.refund_card_layout.addWidget(self.divider)
        self.lbl_field_info = QtWidgets.QLabel(parent=self.refund_card)
        self.lbl_field_info.setObjectName("lbl_field_info")
        self.refund_card_layout.addWidget(self.lbl_field_info)
        self.ticket_info_card = QtWidgets.QFrame(parent=self.refund_card)
        self.ticket_info_card.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.ticket_info_card.setVisible(False)
        self.ticket_info_card.setObjectName("ticket_info_card")
        self.ticket_info_layout = QtWidgets.QVBoxLayout(self.ticket_info_card)
        self.ticket_info_layout.setContentsMargins(16, 14, 16, 14)
        self.ticket_info_layout.setSpacing(10)
        self.ticket_info_layout.setObjectName("ticket_info_layout")
        self.ticket_top_row = QtWidgets.QHBoxLayout()
        self.ticket_top_row.setSpacing(8)
        self.ticket_top_row.setObjectName("ticket_top_row")
        self.lbl_ticket_icon = QtWidgets.QLabel(parent=self.ticket_info_card)
        self.lbl_ticket_icon.setObjectName("lbl_ticket_icon")
        self.ticket_top_row.addWidget(self.lbl_ticket_icon)
        self.ticket_title_col = QtWidgets.QVBoxLayout()
        self.ticket_title_col.setSpacing(2)
        self.ticket_title_col.setObjectName("ticket_title_col")
        self.lbl_ticket_route = QtWidgets.QLabel(parent=self.ticket_info_card)
        self.lbl_ticket_route.setObjectName("lbl_ticket_route")
        self.ticket_title_col.addWidget(self.lbl_ticket_route)
        self.lbl_ticket_type = QtWidgets.QLabel(parent=self.ticket_info_card)
        self.lbl_ticket_type.setObjectName("lbl_ticket_type")
        self.ticket_title_col.addWidget(self.lbl_ticket_type)
        self.ticket_top_row.addLayout(self.ticket_title_col)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.ticket_top_row.addItem(spacerItem4)
        self.badge_status = QtWidgets.QLabel(parent=self.ticket_info_card)
        self.badge_status.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.badge_status.setObjectName("badge_status")
        self.ticket_top_row.addWidget(self.badge_status)
        self.ticket_info_layout.addLayout(self.ticket_top_row)
        self.lbl_ticket_date = QtWidgets.QLabel(parent=self.ticket_info_card)
        self.lbl_ticket_date.setObjectName("lbl_ticket_date")
        self.ticket_info_layout.addWidget(self.lbl_ticket_date)
        self.price_row = QtWidgets.QHBoxLayout()
        self.price_row.setObjectName("price_row")
        self.lbl_ticket_price_caption = QtWidgets.QLabel(parent=self.ticket_info_card)
        self.lbl_ticket_price_caption.setObjectName("lbl_ticket_price_caption")
        self.price_row.addWidget(self.lbl_ticket_price_caption)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.price_row.addItem(spacerItem5)
        self.lbl_ticket_price_value = QtWidgets.QLabel(parent=self.ticket_info_card)
        self.lbl_ticket_price_value.setObjectName("lbl_ticket_price_value")
        self.price_row.addWidget(self.lbl_ticket_price_value)
        self.ticket_info_layout.addLayout(self.price_row)
        self.refund_card_layout.addWidget(self.ticket_info_card)
        self.lbl_empty_state = QtWidgets.QLabel(parent=self.refund_card)
        self.lbl_empty_state.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_empty_state.setWordWrap(True)
        self.lbl_empty_state.setObjectName("lbl_empty_state")
        self.refund_card_layout.addWidget(self.lbl_empty_state)
        self.refund_amount_row = QtWidgets.QFrame(parent=self.refund_card)
        self.refund_amount_row.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.refund_amount_row.setVisible(False)
        self.refund_amount_row.setObjectName("refund_amount_row")
        self.refund_amount_layout = QtWidgets.QHBoxLayout(self.refund_amount_row)
        self.refund_amount_layout.setContentsMargins(16, 12, 16, 12)
        self.refund_amount_layout.setSpacing(8)
        self.refund_amount_layout.setObjectName("refund_amount_layout")
        self.refund_text_col = QtWidgets.QVBoxLayout()
        self.refund_text_col.setSpacing(2)
        self.refund_text_col.setObjectName("refund_text_col")
        self.lbl_refund_caption = QtWidgets.QLabel(parent=self.refund_amount_row)
        self.lbl_refund_caption.setObjectName("lbl_refund_caption")
        self.refund_text_col.addWidget(self.lbl_refund_caption)
        self.lbl_refund_note = QtWidgets.QLabel(parent=self.refund_amount_row)
        self.lbl_refund_note.setObjectName("lbl_refund_note")
        self.refund_text_col.addWidget(self.lbl_refund_note)
        self.refund_amount_layout.addLayout(self.refund_text_col)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.refund_amount_layout.addItem(spacerItem6)
        self.lbl_refund_amount = QtWidgets.QLabel(parent=self.refund_amount_row)
        self.lbl_refund_amount.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_refund_amount.setObjectName("lbl_refund_amount")
        self.refund_amount_layout.addWidget(self.lbl_refund_amount)
        self.refund_card_layout.addWidget(self.refund_amount_row)
        self.root_layout.addWidget(self.refund_card)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.root_layout.addItem(spacerItem7)
        self.btn_confirm_refund = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_confirm_refund.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_confirm_refund.setMinimumSize(QtCore.QSize(0, 52))
        self.btn_confirm_refund.setEnabled(False)
        self.btn_confirm_refund.setObjectName("btn_confirm_refund")
        self.root_layout.addWidget(self.btn_confirm_refund)
        spacerItem8 = QtWidgets.QSpacerItem(0, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.root_layout.addItem(spacerItem8)
        self.lbl_bottom_note = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_bottom_note.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_bottom_note.setWordWrap(True)
        self.lbl_bottom_note.setObjectName("lbl_bottom_note")
        self.root_layout.addWidget(self.lbl_bottom_note)
        RefundWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RefundWindow)

    def retranslateUi(self, RefundWindow):
        _translate = QtCore.QCoreApplication.translate
        RefundWindow.setWindowTitle(_translate("RefundWindow", "Metro Ticket System – Hoàn vé"))
        self.btn_back.setText(_translate("RefundWindow", "←  Quay lại"))
        self.lbl_header_title.setText(_translate("RefundWindow", "↩  Hoàn vé"))
        self.lbl_balance_caption.setText(_translate("RefundWindow", "SỐ DƯ VÍ ĐIỆN TỬ"))
        self.lbl_balance_value.setText(_translate("RefundWindow", "500,000 VNĐ"))
        self.lbl_field_ticket.setText(_translate("RefundWindow", "MÃ VÉ CẦN HOÀN"))
        self.inp_ticket_code.setPlaceholderText(_translate("RefundWindow", "Nhập mã QR hoặc ticket ID..."))
        self.btn_lookup.setText(_translate("RefundWindow", "Tra cứu"))
        self.lbl_field_info.setText(_translate("RefundWindow", "THÔNG TIN VÉ"))
        self.lbl_ticket_icon.setText(_translate("RefundWindow", "🎫"))
        self.lbl_ticket_icon.setStyleSheet(_translate("RefundWindow", "font-size: 22px;"))
        self.lbl_ticket_route.setText(_translate("RefundWindow", "Bến Thành → Suối Tiên"))
        self.lbl_ticket_type.setText(_translate("RefundWindow", "Vé lượt"))
        self.badge_status.setText(_translate("RefundWindow", "CHƯA DÙNG"))
        self.lbl_ticket_date.setText(_translate("RefundWindow", "Ngày mua: 01/06/2026 06:10"))
        self.lbl_ticket_price_caption.setText(_translate("RefundWindow", "Giá vé đã thanh toán"))
        self.lbl_ticket_price_value.setText(_translate("RefundWindow", "39.000 VNĐ"))
        self.lbl_empty_state.setText(_translate("RefundWindow", "🔍  Nhập mã vé và bấm \"Tra cứu\" để xem thông tin"))
        self.lbl_empty_state.setStyleSheet(_translate("RefundWindow", "color: #94A3B8; font-size: 12px; padding: 12px 0px;"))
        self.lbl_refund_caption.setText(_translate("RefundWindow", "SỐ TIỀN ĐƯỢC HOÀN"))
        self.lbl_refund_note.setText(_translate("RefundWindow", "Hoàn 100% vì vé chưa sử dụng"))
        self.lbl_refund_amount.setText(_translate("RefundWindow", "39.000 VNĐ"))
        self.btn_confirm_refund.setText(_translate("RefundWindow", "↩  Xác nhận hoàn vé"))
        self.lbl_bottom_note.setText(_translate("RefundWindow", "⚠  Chỉ hoàn được vé có trạng thái CHƯA DÙNG (UNUSED)"))
