# Form implementation generated from reading ui file 'D:\Nam1\KTLT\K25411_KTLT\UI_KhachHang\KhachHang.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DashboardWindow(object):
    def setupUi(self, DashboardWindow):
        DashboardWindow.setObjectName("DashboardWindow")
        DashboardWindow.resize(440, 680)
        DashboardWindow.setMinimumSize(QtCore.QSize(440, 600))
        DashboardWindow.setStyleSheet("\n"
"/* ── Nền tổng ── */\n"
"QWidget#centralwidget {\n"
"    background-color: #E8F6FD;\n"
"}\n"
"\n"
"/* ── Header ── */\n"
"QFrame#header {\n"
"    background-color: #FFFFFF;\n"
"    border-bottom: 1px solid #B3E0F5;\n"
"}\n"
"QLabel#lbl_avatar {\n"
"    background-color: #29B6F6;\n"
"    border-radius: 22px;\n"
"    color: #FFFFFF;\n"
"    font-size: 15px;\n"
"    font-weight: 700;\n"
"}\n"
"QLabel#lbl_name {\n"
"    color: #0A4D7A;\n"
"    font-size: 15px;\n"
"    font-weight: 700;\n"
"}\n"
"QLabel#lbl_email {\n"
"    color: #3A9EC9;\n"
"    font-size: 12px;\n"
"}\n"
"QPushButton#btn_logout {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #B3E0F5;\n"
"    border-radius: 10px;\n"
"    color: #0288D1;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"    padding: 6px 14px;\n"
"}\n"
"QPushButton#btn_logout:hover {\n"
"    background-color: #E1F5FE;\n"
"    border-color: #29B6F6;\n"
"}\n"
"QPushButton#btn_logout:pressed {\n"
"    background-color: #B3E0F5;\n"
"}\n"
"\n"
"/* ── Wallet card ── */\n"
"QFrame#wallet_card {\n"
"    background: qlineargradient(x1:0,y1:0,x2:1,y2:1,\n"
"        stop:0 #0288D1, stop:0.5 #29B6F6, stop:1 #4FC3F7);\n"
"    border-radius: 18px;\n"
"    border: none;\n"
"}\n"
"QLabel#lbl_wallet_title {\n"
"    color: #E1F5FE;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"}\n"
"QLabel#lbl_balance {\n"
"    color: #FFFFFF;\n"
"    font-size: 30px;\n"
"    font-weight: 700;\n"
"}\n"
"QPushButton#btn_topup {\n"
"    background-color: rgba(255,255,255,0.22);\n"
"    border: 1.5px solid rgba(255,255,255,0.55);\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"    padding: 9px 0px;\n"
"}\n"
"QPushButton#btn_topup:hover {\n"
"    background-color: rgba(255,255,255,0.35);\n"
"}\n"
"QPushButton#btn_topup:pressed {\n"
"    background-color: rgba(255,255,255,0.15);\n"
"}\n"
"QPushButton#btn_history {\n"
"    background-color: rgba(255,255,255,0.12);\n"
"    border: 1.5px solid rgba(255,255,255,0.40);\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"    padding: 9px 0px;\n"
"}\n"
"QPushButton#btn_history:hover {\n"
"    background-color: rgba(255,255,255,0.25);\n"
"}\n"
"QPushButton#btn_history:pressed {\n"
"    background-color: rgba(255,255,255,0.08);\n"
"}\n"
"\n"
"/* ── Menu cards ── */\n"
"QFrame#card_buy,\n"
"QFrame#card_myticket {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 16px;\n"
"    border: 1.5px solid #B3E0F5;\n"
"}\n"
"QFrame#card_buy:hover,\n"
"QFrame#card_myticket:hover {\n"
"    border-color: #29B6F6;\n"
"    background-color: #F0FAFF;\n"
"}\n"
"QLabel#lbl_icon_buy,\n"
"QLabel#lbl_icon_ticket {\n"
"    background-color: #E1F5FE;\n"
"    border-radius: 12px;\n"
"    font-size: 22px;\n"
"}\n"
"QLabel#lbl_menu_title {\n"
"    color: #0A4D7A;\n"
"    font-size: 15px;\n"
"    font-weight: 700;\n"
"}\n"
"QLabel#lbl_menu_sub {\n"
"    color: #3A9EC9;\n"
"    font-size: 12px;\n"
"}\n"
"QPushButton#btn_buy,\n"
"QPushButton#btn_myticket {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    text-align: left;\n"
"}\n"
"\n"
"/* ── Tip banner ── */\n"
"QFrame#tip_banner {\n"
"    background-color: #E1F5FE;\n"
"    border-radius: 14px;\n"
"    border: 1px solid #B3E0F5;\n"
"}\n"
"QLabel#lbl_tip_icon {\n"
"    font-size: 18px;\n"
"}\n"
"QLabel#lbl_tip_title {\n"
"    color: #0288D1;\n"
"    font-size: 13px;\n"
"    font-weight: 700;\n"
"}\n"
"QLabel#lbl_tip_body {\n"
"    color: #0D6FA6;\n"
"    font-size: 12px;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=DashboardWindow)
        self.centralwidget.setGeometry(QtCore.QRect(0, 0, 440, 680))
        self.centralwidget.setObjectName("centralwidget")
        self.root_vbox = QtWidgets.QVBoxLayout(self.centralwidget)
        self.root_vbox.setContentsMargins(0, 0, 0, 0)
        self.root_vbox.setSpacing(0)
        self.root_vbox.setObjectName("root_vbox")
        self.header = QtWidgets.QFrame(parent=self.centralwidget)
        self.header.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.header.setObjectName("header")
        self.header_layout = QtWidgets.QHBoxLayout(self.header)
        self.header_layout.setContentsMargins(20, 14, 20, 14)
        self.header_layout.setSpacing(12)
        self.header_layout.setObjectName("header_layout")
        self.lbl_avatar = QtWidgets.QLabel(parent=self.header)
        self.lbl_avatar.setMinimumSize(QtCore.QSize(44, 44))
        self.lbl_avatar.setMaximumSize(QtCore.QSize(44, 44))
        self.lbl_avatar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_avatar.setObjectName("lbl_avatar")
        self.header_layout.addWidget(self.lbl_avatar)
        self.user_info_vbox = QtWidgets.QVBoxLayout()
        self.user_info_vbox.setSpacing(2)
        self.user_info_vbox.setObjectName("user_info_vbox")
        self.lbl_name = QtWidgets.QLabel(parent=self.header)
        self.lbl_name.setObjectName("lbl_name")
        self.user_info_vbox.addWidget(self.lbl_name)
        self.lbl_email = QtWidgets.QLabel(parent=self.header)
        self.lbl_email.setObjectName("lbl_email")
        self.user_info_vbox.addWidget(self.lbl_email)
        self.header_layout.addLayout(self.user_info_vbox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.header_layout.addItem(spacerItem)
        self.btn_logout = QtWidgets.QPushButton(parent=self.header)
        self.btn_logout.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_logout.setObjectName("btn_logout")
        self.header_layout.addWidget(self.btn_logout)
        self.root_vbox.addWidget(self.header)
        self.scroll_area = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scroll_area.setStyleSheet("QScrollArea { background: transparent; border: none; } QScrollBar:vertical { width: 6px; background: #E8F6FD; } QScrollBar::handle:vertical { background: #B3E0F5; border-radius: 3px; } QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical { height: 0px; }")
        self.scroll_area.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scroll_contents = QtWidgets.QWidget()
        self.scroll_contents.setGeometry(QtCore.QRect(0, 0, 440, 606))
        self.scroll_contents.setStyleSheet("QWidget#scroll_contents { background: transparent; }")
        self.scroll_contents.setObjectName("scroll_contents")
        self.body_vbox = QtWidgets.QVBoxLayout(self.scroll_contents)
        self.body_vbox.setContentsMargins(20, 20, 20, 24)
        self.body_vbox.setSpacing(16)
        self.body_vbox.setObjectName("body_vbox")
        self.wallet_card = QtWidgets.QFrame(parent=self.scroll_contents)
        self.wallet_card.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.wallet_card.setObjectName("wallet_card")
        self.wallet_vbox = QtWidgets.QVBoxLayout(self.wallet_card)
        self.wallet_vbox.setContentsMargins(22, 20, 22, 20)
        self.wallet_vbox.setSpacing(8)
        self.wallet_vbox.setObjectName("wallet_vbox")
        self.lbl_wallet_title = QtWidgets.QLabel(parent=self.wallet_card)
        self.lbl_wallet_title.setObjectName("lbl_wallet_title")
        self.wallet_vbox.addWidget(self.lbl_wallet_title)
        self.lbl_balance = QtWidgets.QLabel(parent=self.wallet_card)
        self.lbl_balance.setObjectName("lbl_balance")
        self.wallet_vbox.addWidget(self.lbl_balance)
        spacerItem1 = QtWidgets.QSpacerItem(0, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.wallet_vbox.addItem(spacerItem1)
        self.wallet_btn_row = QtWidgets.QHBoxLayout()
        self.wallet_btn_row.setSpacing(12)
        self.wallet_btn_row.setObjectName("wallet_btn_row")
        self.btn_topup = QtWidgets.QPushButton(parent=self.wallet_card)
        self.btn_topup.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_topup.setObjectName("btn_topup")
        self.wallet_btn_row.addWidget(self.btn_topup)
        self.btn_history = QtWidgets.QPushButton(parent=self.wallet_card)
        self.btn_history.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_history.setObjectName("btn_history")
        self.wallet_btn_row.addWidget(self.btn_history)
        self.wallet_vbox.addLayout(self.wallet_btn_row)
        self.body_vbox.addWidget(self.wallet_card)
        self.menu_grid = QtWidgets.QHBoxLayout()
        self.menu_grid.setSpacing(14)
        self.menu_grid.setObjectName("menu_grid")
        self.card_buy = QtWidgets.QFrame(parent=self.scroll_contents)
        self.card_buy.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.card_buy.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.card_buy.setObjectName("card_buy")
        self.card_buy_vbox = QtWidgets.QVBoxLayout(self.card_buy)
        self.card_buy_vbox.setContentsMargins(16, 18, 16, 18)
        self.card_buy_vbox.setSpacing(10)
        self.card_buy_vbox.setObjectName("card_buy_vbox")
        self.lbl_icon_buy = QtWidgets.QLabel(parent=self.card_buy)
        self.lbl_icon_buy.setMinimumSize(QtCore.QSize(44, 44))
        self.lbl_icon_buy.setMaximumSize(QtCore.QSize(44, 44))
        self.lbl_icon_buy.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_icon_buy.setObjectName("lbl_icon_buy")
        self.card_buy_vbox.addWidget(self.lbl_icon_buy)
        self.lbl_menu_title = QtWidgets.QLabel(parent=self.card_buy)
        self.lbl_menu_title.setObjectName("lbl_menu_title")
        self.card_buy_vbox.addWidget(self.lbl_menu_title)
        self.lbl_menu_sub = QtWidgets.QLabel(parent=self.card_buy)
        self.lbl_menu_sub.setWordWrap(True)
        self.lbl_menu_sub.setObjectName("lbl_menu_sub")
        self.card_buy_vbox.addWidget(self.lbl_menu_sub)
        spacerItem2 = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.card_buy_vbox.addItem(spacerItem2)
        self.menu_grid.addWidget(self.card_buy)
        self.card_myticket = QtWidgets.QFrame(parent=self.scroll_contents)
        self.card_myticket.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.card_myticket.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.card_myticket.setObjectName("card_myticket")
        self.card_ticket_vbox = QtWidgets.QVBoxLayout(self.card_myticket)
        self.card_ticket_vbox.setContentsMargins(16, 18, 16, 18)
        self.card_ticket_vbox.setSpacing(10)
        self.card_ticket_vbox.setObjectName("card_ticket_vbox")
        self.lbl_icon_ticket = QtWidgets.QLabel(parent=self.card_myticket)
        self.lbl_icon_ticket.setMinimumSize(QtCore.QSize(44, 44))
        self.lbl_icon_ticket.setMaximumSize(QtCore.QSize(44, 44))
        self.lbl_icon_ticket.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_icon_ticket.setObjectName("lbl_icon_ticket")
        self.card_ticket_vbox.addWidget(self.lbl_icon_ticket)
        self.lbl_menu_title_2 = QtWidgets.QLabel(parent=self.card_myticket)
        self.lbl_menu_title_2.setStyleSheet("color: #0A4D7A; font-size: 15px; font-weight: 700;")
        self.lbl_menu_title_2.setObjectName("lbl_menu_title_2")
        self.card_ticket_vbox.addWidget(self.lbl_menu_title_2)
        self.lbl_menu_sub_2 = QtWidgets.QLabel(parent=self.card_myticket)
        self.lbl_menu_sub_2.setStyleSheet("color: #3A9EC9; font-size: 12px;")
        self.lbl_menu_sub_2.setWordWrap(True)
        self.lbl_menu_sub_2.setObjectName("lbl_menu_sub_2")
        self.card_ticket_vbox.addWidget(self.lbl_menu_sub_2)
        spacerItem3 = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.card_ticket_vbox.addItem(spacerItem3)
        self.menu_grid.addWidget(self.card_myticket)
        self.body_vbox.addLayout(self.menu_grid)
        self.tip_banner = QtWidgets.QFrame(parent=self.scroll_contents)
        self.tip_banner.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tip_banner.setObjectName("tip_banner")
        self.tip_layout = QtWidgets.QHBoxLayout(self.tip_banner)
        self.tip_layout.setContentsMargins(16, 14, 16, 14)
        self.tip_layout.setSpacing(10)
        self.tip_layout.setObjectName("tip_layout")
        self.lbl_tip_icon = QtWidgets.QLabel(parent=self.tip_banner)
        self.lbl_tip_icon.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.lbl_tip_icon.setObjectName("lbl_tip_icon")
        self.tip_layout.addWidget(self.lbl_tip_icon)
        self.tip_text_vbox = QtWidgets.QVBoxLayout()
        self.tip_text_vbox.setSpacing(3)
        self.tip_text_vbox.setObjectName("tip_text_vbox")
        self.lbl_tip_title = QtWidgets.QLabel(parent=self.tip_banner)
        self.lbl_tip_title.setObjectName("lbl_tip_title")
        self.tip_text_vbox.addWidget(self.lbl_tip_title)
        self.lbl_tip_body = QtWidgets.QLabel(parent=self.tip_banner)
        self.lbl_tip_body.setWordWrap(True)
        self.lbl_tip_body.setObjectName("lbl_tip_body")
        self.tip_text_vbox.addWidget(self.lbl_tip_body)
        self.tip_layout.addLayout(self.tip_text_vbox)
        self.body_vbox.addWidget(self.tip_banner)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.body_vbox.addItem(spacerItem4)
        self.scroll_area.setWidget(self.scroll_contents)
        self.root_vbox.addWidget(self.scroll_area)
        DashboardWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(DashboardWindow)
        QtCore.QMetaObject.connectSlotsByName(DashboardWindow)

    def retranslateUi(self, DashboardWindow):
        _translate = QtCore.QCoreApplication.translate
        DashboardWindow.setWindowTitle(_translate("DashboardWindow", "Metro Ticket System – Dashboard"))
        self.lbl_avatar.setText(_translate("DashboardWindow", "KH"))
        self.lbl_name.setText(_translate("DashboardWindow", "Khách Hàng #123"))
        self.lbl_email.setText(_translate("DashboardWindow", "customer@metro.vn"))
        self.btn_logout.setText(_translate("DashboardWindow", "⇥  Đăng xuất"))
        self.lbl_wallet_title.setText(_translate("DashboardWindow", "Số dư ví"))
        self.lbl_balance.setText(_translate("DashboardWindow", "500,000 VNĐ"))
        self.btn_topup.setText(_translate("DashboardWindow", "+  Nạp tiền  ↗"))
        self.btn_history.setText(_translate("DashboardWindow", "⏱  Lịch sử"))
        self.lbl_icon_buy.setText(_translate("DashboardWindow", "🎫"))
        self.lbl_menu_title.setText(_translate("DashboardWindow", "Mua vé ↗"))
        self.lbl_menu_sub.setText(_translate("DashboardWindow", "Chọn tuyến và mua vé"))
        self.lbl_icon_ticket.setText(_translate("DashboardWindow", "📱"))
        self.lbl_menu_title_2.setText(_translate("DashboardWindow", "Vé của tôi ↗"))
        self.lbl_menu_sub_2.setText(_translate("DashboardWindow", "Xem vé đã mua"))
        self.lbl_tip_icon.setText(_translate("DashboardWindow", "💡"))
        self.lbl_tip_title.setText(_translate("DashboardWindow", "Mẹo tiết kiệm"))
        self.lbl_tip_body.setText(_translate("DashboardWindow", "Mua vé tháng để tiết kiệm đến 30% chi phí đi lại!"))
