# Form implementation generated from reading ui file 'NapTien_Ver2.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TopUpWindow(object):
    def setupUi(self, TopUpWindow):
        TopUpWindow.setObjectName("TopUpWindow")
        TopUpWindow.resize(460, 700)
        TopUpWindow.setMinimumSize(QtCore.QSize(420, 640))
        TopUpWindow.setStyleSheet("\n"
"/* ── Nền tổng: gradient xanh đậm (đồng bộ Login/Dashboard) ── */\n"
"QWidget#centralwidget {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0.3, y2:1,\n"
"        stop:0 #0D1F3C,\n"
"        stop:0.4 #0A3060,\n"
"        stop:0.7 #0D4080,\n"
"        stop:1   #1A5FA8);\n"
"}\n"
"\n"
"/* ── Header row ── */\n"
"QPushButton#btn_back {\n"
"    background: rgba(255,255,255,0.10);\n"
"    border: 1px solid rgba(255,255,255,0.18);\n"
"    border-radius: 10px;\n"
"    color: #E0F2FE;\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    padding: 6px 14px;\n"
"}\n"
"QPushButton#btn_back:hover { background: rgba(255,255,255,0.18); }\n"
"\n"
"QLabel#lbl_header_title {\n"
"    color: #FFFFFF;\n"
"    font-size: 17px;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"/* ── Card số dư hiện tại (gradient xanh, giống dashboard) ── */\n"
"QFrame#balance_card {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #0EA5E9, stop:0.5 #0284C7, stop:1 #075985);\n"
"    border-radius: 20px;\n"
"    border-top: 1px solid rgba(255,255,255,0.25);\n"
"}\n"
"QLabel#lbl_balance_caption {\n"
"    color: rgba(255,255,255,0.85);\n"
"    font-size: 11px;\n"
"    font-weight: 700;\n"
"    letter-spacing: 1px;\n"
"}\n"
"QLabel#lbl_balance_value {\n"
"    color: #FFFFFF;\n"
"    font-size: 30px;\n"
"    font-weight: 800;\n"
"}\n"
"\n"
"/* ── Card trắng chứa form nạp tiền ── */\n"
"QFrame#form_card {\n"
"    background-color: rgba(255, 255, 255, 0.97);\n"
"    border-radius: 22px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.15);\n"
"}\n"
"\n"
"QLabel#lbl_field_amount,\n"
"QLabel#lbl_field_quick,\n"
"QLabel#lbl_field_method {\n"
"    color: #0369A1;\n"
"    font-size: 11px;\n"
"    font-weight: 700;\n"
"    letter-spacing: 0.8px;\n"
"}\n"
"\n"
"/* ── Ô nhập số tiền ── */\n"
"QLineEdit#inp_amount {\n"
"    background-color: #F0F9FF;\n"
"    border: 1.5px solid #BAE6FD;\n"
"    border-radius: 12px;\n"
"    padding: 12px 14px;\n"
"    font-size: 18px;\n"
"    font-weight: 700;\n"
"    color: #0C4A6E;\n"
"    selection-background-color: #29B6F6;\n"
"}\n"
"QLineEdit#inp_amount:hover { border-color: #38BDF8; background-color: #E8F6FD; }\n"
"QLineEdit#inp_amount:focus { border-color: #0284C7; background-color: #FFFFFF; }\n"
"\n"
"/* ── Quick amount chips ── */\n"
"QPushButton#btn_quick_1, QPushButton#btn_quick_2,\n"
"QPushButton#btn_quick_3, QPushButton#btn_quick_4 {\n"
"    background-color: #F0F9FF;\n"
"    border: 1.5px solid #BAE6FD;\n"
"    border-radius: 12px;\n"
"    color: #0369A1;\n"
"    font-size: 13px;\n"
"    font-weight: 700;\n"
"    padding: 10px 0px;\n"
"}\n"
"QPushButton#btn_quick_1:hover, QPushButton#btn_quick_2:hover,\n"
"QPushButton#btn_quick_3:hover, QPushButton#btn_quick_4:hover {\n"
"    border-color: #38BDF8; background-color: #E8F6FD;\n"
"}\n"
"QPushButton#btn_quick_1:checked, QPushButton#btn_quick_2:checked,\n"
"QPushButton#btn_quick_3:checked, QPushButton#btn_quick_4:checked {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #0284C7, stop:1 #38BDF8);\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"}\n"
"\n"
"/* ── Dropdown phương thức thanh toán ── */\n"
"QComboBox#cbo_payment_method {\n"
"    background-color: #F0F9FF;\n"
"    border: 1.5px solid #BAE6FD;\n"
"    border-radius: 12px;\n"
"    padding: 10px 14px;\n"
"    font-size: 14px;\n"
"    color: #0C4A6E;\n"
"}\n"
"QComboBox#cbo_payment_method:hover { border-color: #38BDF8; }\n"
"QComboBox#cbo_payment_method::drop-down { border: none; width: 28px; }\n"
"QComboBox#cbo_payment_method QAbstractItemView {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #BAE6FD;\n"
"    border-radius: 8px;\n"
"    selection-background-color: #BAE6FD;\n"
"    color: #0C4A6E;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"/* ── Nút xác nhận nạp tiền (gradient, giống btn_login) ── */\n"
"QPushButton#btn_confirm_topup {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #0284C7, stop:0.5 #0EA5E9, stop:1 #38BDF8);\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 14px;\n"
"    font-size: 15px;\n"
"    font-weight: 700;\n"
"    padding: 14px 0px;\n"
"    border-top: 1px solid rgba(255,255,255,0.2);\n"
"}\n"
"QPushButton#btn_confirm_topup:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #0369A1, stop:0.5 #0284C7, stop:1 #0EA5E9);\n"
"}\n"
"QPushButton#btn_confirm_topup:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #075985, stop:1 #0284C7);\n"
"}\n"
"QPushButton#btn_confirm_topup:disabled {\n"
"    background: #BAE6FD;\n"
"    color: rgba(255,255,255,0.6);\n"
"}\n"
"\n"
"QLabel#lbl_note {\n"
"    color: #64748B;\n"
"    font-size: 11px;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=TopUpWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.root_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.root_layout.setContentsMargins(28, 24, 28, 28)
        self.root_layout.setSpacing(0)
        self.root_layout.setObjectName("root_layout")
        self.header_row = QtWidgets.QHBoxLayout()
        self.header_row.setObjectName("header_row")
        self.btn_back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_back.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_back.setFlat(True)
        self.btn_back.setObjectName("btn_back")
        self.header_row.addWidget(self.btn_back)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.header_row.addItem(spacerItem)
        self.lbl_header_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_header_title.setObjectName("lbl_header_title")
        self.header_row.addWidget(self.lbl_header_title)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.header_row.addItem(spacerItem1)
        self.root_layout.addLayout(self.header_row)
        spacerItem2 = QtWidgets.QSpacerItem(0, 18, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.root_layout.addItem(spacerItem2)
        self.balance_card = QtWidgets.QFrame(parent=self.centralwidget)
        self.balance_card.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.balance_card.setObjectName("balance_card")
        self.balance_layout = QtWidgets.QVBoxLayout(self.balance_card)
        self.balance_layout.setContentsMargins(22, 18, 22, 20)
        self.balance_layout.setObjectName("balance_layout")
        self.lbl_balance_caption = QtWidgets.QLabel(parent=self.balance_card)
        self.lbl_balance_caption.setObjectName("lbl_balance_caption")
        self.balance_layout.addWidget(self.lbl_balance_caption)
        spacerItem3 = QtWidgets.QSpacerItem(0, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.balance_layout.addItem(spacerItem3)
        self.lbl_balance_value = QtWidgets.QLabel(parent=self.balance_card)
        self.lbl_balance_value.setObjectName("lbl_balance_value")
        self.balance_layout.addWidget(self.lbl_balance_value)
        self.root_layout.addWidget(self.balance_card)
        spacerItem4 = QtWidgets.QSpacerItem(0, 18, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.root_layout.addItem(spacerItem4)
        self.form_card = QtWidgets.QFrame(parent=self.centralwidget)
        self.form_card.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.form_card.setObjectName("form_card")
        self.form_layout = QtWidgets.QVBoxLayout(self.form_card)
        self.form_layout.setContentsMargins(26, 24, 26, 24)
        self.form_layout.setSpacing(0)
        self.form_layout.setObjectName("form_layout")
        self.lbl_field_amount = QtWidgets.QLabel(parent=self.form_card)
        self.lbl_field_amount.setObjectName("lbl_field_amount")
        self.form_layout.addWidget(self.lbl_field_amount)
        spacerItem5 = QtWidgets.QSpacerItem(0, 7, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.form_layout.addItem(spacerItem5)
        self.inp_amount = QtWidgets.QLineEdit(parent=self.form_card)
        self.inp_amount.setClearButtonEnabled(True)
        self.inp_amount.setObjectName("inp_amount")
        self.form_layout.addWidget(self.inp_amount)
        spacerItem6 = QtWidgets.QSpacerItem(0, 18, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.form_layout.addItem(spacerItem6)
        self.lbl_field_quick = QtWidgets.QLabel(parent=self.form_card)
        self.lbl_field_quick.setObjectName("lbl_field_quick")
        self.form_layout.addWidget(self.lbl_field_quick)
        spacerItem7 = QtWidgets.QSpacerItem(0, 7, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.form_layout.addItem(spacerItem7)
        self.quick_row = QtWidgets.QHBoxLayout()
        self.quick_row.setSpacing(8)
        self.quick_row.setObjectName("quick_row")
        self.btn_quick_1 = QtWidgets.QPushButton(parent=self.form_card)
        self.btn_quick_1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_quick_1.setCheckable(True)
        self.btn_quick_1.setAutoExclusive(True)
        self.btn_quick_1.setObjectName("btn_quick_1")
        self.quick_row.addWidget(self.btn_quick_1)
        self.btn_quick_2 = QtWidgets.QPushButton(parent=self.form_card)
        self.btn_quick_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_quick_2.setCheckable(True)
        self.btn_quick_2.setAutoExclusive(True)
        self.btn_quick_2.setObjectName("btn_quick_2")
        self.quick_row.addWidget(self.btn_quick_2)
        self.btn_quick_3 = QtWidgets.QPushButton(parent=self.form_card)
        self.btn_quick_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_quick_3.setCheckable(True)
        self.btn_quick_3.setAutoExclusive(True)
        self.btn_quick_3.setObjectName("btn_quick_3")
        self.quick_row.addWidget(self.btn_quick_3)
        self.btn_quick_4 = QtWidgets.QPushButton(parent=self.form_card)
        self.btn_quick_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_quick_4.setCheckable(True)
        self.btn_quick_4.setAutoExclusive(True)
        self.btn_quick_4.setObjectName("btn_quick_4")
        self.quick_row.addWidget(self.btn_quick_4)
        self.form_layout.addLayout(self.quick_row)
        spacerItem8 = QtWidgets.QSpacerItem(0, 18, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.form_layout.addItem(spacerItem8)
        self.lbl_field_method = QtWidgets.QLabel(parent=self.form_card)
        self.lbl_field_method.setObjectName("lbl_field_method")
        self.form_layout.addWidget(self.lbl_field_method)
        spacerItem9 = QtWidgets.QSpacerItem(0, 7, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.form_layout.addItem(spacerItem9)
        self.cbo_payment_method = QtWidgets.QComboBox(parent=self.form_card)
        self.cbo_payment_method.setObjectName("cbo_payment_method")
        self.cbo_payment_method.addItem("")
        self.cbo_payment_method.addItem("")
        self.cbo_payment_method.addItem("")
        self.cbo_payment_method.addItem("")
        self.form_layout.addWidget(self.cbo_payment_method)
        spacerItem10 = QtWidgets.QSpacerItem(0, 24, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.form_layout.addItem(spacerItem10)
        self.btn_confirm_topup = QtWidgets.QPushButton(parent=self.form_card)
        self.btn_confirm_topup.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_confirm_topup.setDefault(True)
        self.btn_confirm_topup.setObjectName("btn_confirm_topup")
        self.form_layout.addWidget(self.btn_confirm_topup)
        spacerItem11 = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.form_layout.addItem(spacerItem11)
        self.lbl_note = QtWidgets.QLabel(parent=self.form_card)
        self.lbl_note.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_note.setWordWrap(True)
        self.lbl_note.setObjectName("lbl_note")
        self.form_layout.addWidget(self.lbl_note)
        self.root_layout.addWidget(self.form_card)
        spacerItem12 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.root_layout.addItem(spacerItem12)
        TopUpWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(TopUpWindow)
        QtCore.QMetaObject.connectSlotsByName(TopUpWindow)
        TopUpWindow.setTabOrder(self.inp_amount, self.btn_quick_1)
        TopUpWindow.setTabOrder(self.btn_quick_1, self.btn_quick_2)
        TopUpWindow.setTabOrder(self.btn_quick_2, self.btn_quick_3)
        TopUpWindow.setTabOrder(self.btn_quick_3, self.btn_quick_4)
        TopUpWindow.setTabOrder(self.btn_quick_4, self.cbo_payment_method)
        TopUpWindow.setTabOrder(self.cbo_payment_method, self.btn_confirm_topup)

    def retranslateUi(self, TopUpWindow):
        _translate = QtCore.QCoreApplication.translate
        TopUpWindow.setWindowTitle(_translate("TopUpWindow", "Metro Ticket System – Nạp tiền"))
        self.btn_back.setText(_translate("TopUpWindow", "←  Quay lại"))
        self.lbl_header_title.setText(_translate("TopUpWindow", "Nạp tiền vào ví"))
        self.lbl_balance_caption.setText(_translate("TopUpWindow", "💳  SỐ DƯ HIỆN TẠI"))
        self.lbl_balance_value.setText(_translate("TopUpWindow", "500,000 VNĐ"))
        self.lbl_field_amount.setText(_translate("TopUpWindow", "SỐ TIỀN NẠP (VNĐ)"))
        self.inp_amount.setPlaceholderText(_translate("TopUpWindow", "Nhập số tiền muốn nạp..."))
        self.lbl_field_quick.setText(_translate("TopUpWindow", "CHỌN NHANH"))
        self.btn_quick_1.setText(_translate("TopUpWindow", "50,000"))
        self.btn_quick_2.setText(_translate("TopUpWindow", "100,000"))
        self.btn_quick_3.setText(_translate("TopUpWindow", "200,000"))
        self.btn_quick_4.setText(_translate("TopUpWindow", "500,000"))
        self.lbl_field_method.setText(_translate("TopUpWindow", "PHƯƠNG THỨC THANH TOÁN"))
        self.cbo_payment_method.setItemText(0, _translate("TopUpWindow", "Thẻ ngân hàng"))
        self.cbo_payment_method.setItemText(1, _translate("TopUpWindow", "Thẻ tín dụng"))
        self.cbo_payment_method.setItemText(2, _translate("TopUpWindow", "MoMo"))
        self.cbo_payment_method.setItemText(3, _translate("TopUpWindow", "VNPay"))
        self.btn_confirm_topup.setText(_translate("TopUpWindow", "Xác nhận nạp tiền  ↗"))
        self.lbl_note.setText(_translate("TopUpWindow", "* Giao dịch sẽ được ghi vào lịch sử nạp tiền và cộng vào ví ngay lập tức."))
