# Form implementation generated from reading ui file 'D:\Nam1\KTLT\K25411_KTLT\UI_KhachHang\QR.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_QRPaymentDialog(object):
    def setupUi(self, QRPaymentDialog):
        QRPaymentDialog.setObjectName("QRPaymentDialog")
        QRPaymentDialog.resize(420, 674)
        QRPaymentDialog.setStyleSheet("\n"
"/* ===== GLOBAL ===== */\n"
"QWidget#centralwidget {\n"
"    background-color: #E8F6FD;\n"
"    font-family: \"Segoe UI\", \"Arial\", sans-serif;\n"
"}\n"
"\n"
"/* ===== MAIN CARD ===== */\n"
"QFrame#mainCard {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #B3E0F5;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"/* ===== SUCCESS ICON CIRCLE ===== */\n"
"QLabel#iconCircle {\n"
"    background-color: qradialgradient(\n"
"        cx:0.5, cy:0.5, radius:0.5,\n"
"        fx:0.5, fy:0.5,\n"
"        stop:0 #FFFFFF,\n"
"        stop:1 #C8EFFD\n"
"    );\n"
"    border: 2.5px solid #29B6F6;\n"
"    border-radius: 28px;\n"
"    color: #0A7EC2;\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"\n"
"/* ===== TITLE ===== */\n"
"QLabel#titleLabel {\n"
"    color: #0A4D7A;\n"
"    font-size: 20px;\n"
"    font-weight: 700;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"\n"
"/* ===== TICKET CODE ===== */\n"
"QLabel#ticketCodeLabel {\n"
"    color: #3A9EC9;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"\n"
"/* ===== QR FRAME ===== */\n"
"QFrame#qrFrame {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #B3E0F5;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"/* ===== QR LABEL ===== */\n"
"QLabel#qrLabel {\n"
"    background-color: #FFFFFF;\n"
"    border: none;\n"
"    qproperty-alignment: AlignHCenter | AlignVCenter;\n"
"}\n"
"\n"
"/* ===== QR HINT ===== */\n"
"QLabel#qrHintLabel {\n"
"    color: #3A9EC9;\n"
"    font-size: 12px;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"\n"
"/* ===== INFO BANNER ===== */\n"
"QFrame#infoBanner {\n"
"    background-color: #E1F5FE;\n"
"    border: 1.5px solid #B3E0F5;\n"
"    border-radius: 14px;\n"
"}\n"
"\n"
"/* ===== INFO ROW LABELS ===== */\n"
"QLabel#infoKeyLabel {\n"
"    color: #0288D1;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QLabel#infoValueLabel {\n"
"    color: #0A4D7A;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"    qproperty-alignment: AlignRight | AlignVCenter;\n"
"}\n"
"\n"
"/* ===== STATUS BADGE ===== */\n"
"QLabel#statusBadge {\n"
"    background-color: #E8F6FD;\n"
"    border: 1px solid #B3E0F5;\n"
"    border-radius: 10px;\n"
"    color: #0288D1;\n"
"    font-size: 12px;\n"
"    font-weight: 600;\n"
"    padding: 3px 12px;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"\n"
"/* ===== DIVIDER ===== */\n"
"QFrame#dividerLine {\n"
"    background-color: #B3E0F5;\n"
"    border: none;\n"
"    max-height: 1px;\n"
"}\n"
"\n"
"/* ===== SECONDARY BUTTONS ===== */\n"
"QPushButton#btnDownload,\n"
"QPushButton#btnShare {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #B3E0F5;\n"
"    border-radius: 12px;\n"
"    color: #0288D1;\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    padding: 10px 0px;\n"
"}\n"
"\n"
"QPushButton#btnDownload:hover,\n"
"QPushButton#btnShare:hover {\n"
"    background-color: #E8F6FD;\n"
"    border-color: #29B6F6;\n"
"    color: #0A4D7A;\n"
"}\n"
"\n"
"QPushButton#btnDownload:pressed,\n"
"QPushButton#btnShare:pressed {\n"
"    background-color: #B3E0F5;\n"
"}\n"
"\n"
"/* ===== PRIMARY BUTTON ===== */\n"
"QPushButton#btnHome {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #00C6FB,\n"
"        stop:0.5 #0288D1,\n"
"        stop:1 #005B9F\n"
"    );\n"
"    border: none;\n"
"    border-radius: 14px;\n"
"    color: #FFFFFF;\n"
"    font-size: 16px;\n"
"    font-weight: 700;\n"
"    padding: 14px 0px;\n"
"}\n"
"\n"
"QPushButton#btnHome:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #40D4FF,\n"
"        stop:0.5 #039BE5,\n"
"        stop:1 #0277BD\n"
"    );\n"
"}\n"
"\n"
"QPushButton#btnHome:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #0288D1,\n"
"        stop:0.5 #0277BD,\n"
"        stop:1 #01579B\n"
"    );\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=QRPaymentDialog)
        self.centralwidget.setGeometry(QtCore.QRect(0, 0, 420, 674))
        self.centralwidget.setObjectName("centralwidget")
        self.outerLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.outerLayout.setContentsMargins(20, 24, 20, 24)
        self.outerLayout.setSpacing(0)
        self.outerLayout.setObjectName("outerLayout")
        self.iconRowLayout = QtWidgets.QHBoxLayout()
        self.iconRowLayout.setObjectName("iconRowLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.iconRowLayout.addItem(spacerItem)
        self.iconCircle = QtWidgets.QLabel(parent=self.centralwidget)
        self.iconCircle.setMinimumSize(QtCore.QSize(56, 56))
        self.iconCircle.setMaximumSize(QtCore.QSize(56, 56))
        self.iconCircle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.iconCircle.setObjectName("iconCircle")
        self.iconRowLayout.addWidget(self.iconCircle)
        spacerItem1 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.iconRowLayout.addItem(spacerItem1)
        self.outerLayout.addLayout(self.iconRowLayout)
        spacerItem2 = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.outerLayout.addItem(spacerItem2)
        self.titleLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.outerLayout.addWidget(self.titleLabel)
        spacerItem3 = QtWidgets.QSpacerItem(0, 4, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.outerLayout.addItem(spacerItem3)
        self.ticketCodeLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.ticketCodeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ticketCodeLabel.setObjectName("ticketCodeLabel")
        self.outerLayout.addWidget(self.ticketCodeLabel)
        spacerItem4 = QtWidgets.QSpacerItem(0, 16, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.outerLayout.addItem(spacerItem4)
        self.qrFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.qrFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.qrFrame.setObjectName("qrFrame")
        self.qrLayout = QtWidgets.QVBoxLayout(self.qrFrame)
        self.qrLayout.setContentsMargins(24, 20, 24, 16)
        self.qrLayout.setSpacing(8)
        self.qrLayout.setObjectName("qrLayout")
        self.qrCenterLayout = QtWidgets.QHBoxLayout()
        self.qrCenterLayout.setObjectName("qrCenterLayout")
        spacerItem5 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.qrCenterLayout.addItem(spacerItem5)
        self.qrLabel = QtWidgets.QLabel(parent=self.qrFrame)
        self.qrLabel.setMinimumSize(QtCore.QSize(180, 180))
        self.qrLabel.setMaximumSize(QtCore.QSize(220, 220))
        self.qrLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.qrLabel.setObjectName("qrLabel")
        self.qrCenterLayout.addWidget(self.qrLabel)
        spacerItem6 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.qrCenterLayout.addItem(spacerItem6)
        self.qrLayout.addLayout(self.qrCenterLayout)
        self.qrHintLabel = QtWidgets.QLabel(parent=self.qrFrame)
        self.qrHintLabel.setStyleSheet("color:#7DD3FC; font-size:12px;")
        self.qrHintLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.qrHintLabel.setObjectName("qrHintLabel")
        self.qrLayout.addWidget(self.qrHintLabel)
        self.outerLayout.addWidget(self.qrFrame)
        spacerItem7 = QtWidgets.QSpacerItem(0, 14, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.outerLayout.addItem(spacerItem7)
        self.infoBanner = QtWidgets.QFrame(parent=self.centralwidget)
        self.infoBanner.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.infoBanner.setObjectName("infoBanner")
        self.infoLayout = QtWidgets.QVBoxLayout(self.infoBanner)
        self.infoLayout.setContentsMargins(16, 12, 16, 12)
        self.infoLayout.setSpacing(0)
        self.infoLayout.setObjectName("infoLayout")
        self.rowTuyen = QtWidgets.QHBoxLayout()
        self.rowTuyen.setObjectName("rowTuyen")
        self.lblTuyenKey = QtWidgets.QLabel(parent=self.infoBanner)
        self.lblTuyenKey.setObjectName("lblTuyenKey")
        self.rowTuyen.addWidget(self.lblTuyenKey)
        spacerItem8 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.rowTuyen.addItem(spacerItem8)
        self.lblTuyenVal = QtWidgets.QLabel(parent=self.infoBanner)
        self.lblTuyenVal.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblTuyenVal.setObjectName("lblTuyenVal")
        self.rowTuyen.addWidget(self.lblTuyenVal)
        self.infoLayout.addLayout(self.rowTuyen)
        self.divider1 = QtWidgets.QFrame(parent=self.infoBanner)
        self.divider1.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.divider1.setObjectName("divider1")
        self.infoLayout.addWidget(self.divider1)
        self.rowHanhTrinh = QtWidgets.QHBoxLayout()
        self.rowHanhTrinh.setObjectName("rowHanhTrinh")
        self.lblHTKey = QtWidgets.QLabel(parent=self.infoBanner)
        self.lblHTKey.setObjectName("lblHTKey")
        self.rowHanhTrinh.addWidget(self.lblHTKey)
        spacerItem9 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.rowHanhTrinh.addItem(spacerItem9)
        self.lblHTVal = QtWidgets.QLabel(parent=self.infoBanner)
        self.lblHTVal.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblHTVal.setObjectName("lblHTVal")
        self.rowHanhTrinh.addWidget(self.lblHTVal)
        self.infoLayout.addLayout(self.rowHanhTrinh)
        self.divider2 = QtWidgets.QFrame(parent=self.infoBanner)
        self.divider2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.divider2.setObjectName("divider2")
        self.infoLayout.addWidget(self.divider2)
        self.rowLoaiVe = QtWidgets.QHBoxLayout()
        self.rowLoaiVe.setObjectName("rowLoaiVe")
        self.lblLVKey = QtWidgets.QLabel(parent=self.infoBanner)
        self.lblLVKey.setObjectName("lblLVKey")
        self.rowLoaiVe.addWidget(self.lblLVKey)
        spacerItem10 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.rowLoaiVe.addItem(spacerItem10)
        self.lblLVVal = QtWidgets.QLabel(parent=self.infoBanner)
        self.lblLVVal.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblLVVal.setObjectName("lblLVVal")
        self.rowLoaiVe.addWidget(self.lblLVVal)
        self.infoLayout.addLayout(self.rowLoaiVe)
        self.divider3 = QtWidgets.QFrame(parent=self.infoBanner)
        self.divider3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.divider3.setObjectName("divider3")
        self.infoLayout.addWidget(self.divider3)
        self.rowGiaVe = QtWidgets.QHBoxLayout()
        self.rowGiaVe.setObjectName("rowGiaVe")
        self.lblGVKey = QtWidgets.QLabel(parent=self.infoBanner)
        self.lblGVKey.setObjectName("lblGVKey")
        self.rowGiaVe.addWidget(self.lblGVKey)
        spacerItem11 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.rowGiaVe.addItem(spacerItem11)
        self.lblGVVal = QtWidgets.QLabel(parent=self.infoBanner)
        self.lblGVVal.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblGVVal.setObjectName("lblGVVal")
        self.rowGiaVe.addWidget(self.lblGVVal)
        self.infoLayout.addLayout(self.rowGiaVe)
        self.divider4 = QtWidgets.QFrame(parent=self.infoBanner)
        self.divider4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.divider4.setObjectName("divider4")
        self.infoLayout.addWidget(self.divider4)
        self.rowNgayMua = QtWidgets.QHBoxLayout()
        self.rowNgayMua.setObjectName("rowNgayMua")
        self.lblNMKey = QtWidgets.QLabel(parent=self.infoBanner)
        self.lblNMKey.setObjectName("lblNMKey")
        self.rowNgayMua.addWidget(self.lblNMKey)
        spacerItem12 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.rowNgayMua.addItem(spacerItem12)
        self.lblNMVal = QtWidgets.QLabel(parent=self.infoBanner)
        self.lblNMVal.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblNMVal.setObjectName("lblNMVal")
        self.rowNgayMua.addWidget(self.lblNMVal)
        self.infoLayout.addLayout(self.rowNgayMua)
        self.divider5 = QtWidgets.QFrame(parent=self.infoBanner)
        self.divider5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.divider5.setObjectName("divider5")
        self.infoLayout.addWidget(self.divider5)
        self.rowTrangThai = QtWidgets.QHBoxLayout()
        self.rowTrangThai.setObjectName("rowTrangThai")
        self.lblTTKey = QtWidgets.QLabel(parent=self.infoBanner)
        self.lblTTKey.setObjectName("lblTTKey")
        self.rowTrangThai.addWidget(self.lblTTKey)
        spacerItem13 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.rowTrangThai.addItem(spacerItem13)
        self.statusBadge = QtWidgets.QLabel(parent=self.infoBanner)
        self.statusBadge.setStyleSheet("color:#0A4D7A;font-size:13px;font-weight:600;")
        self.statusBadge.setObjectName("statusBadge")
        self.rowTrangThai.addWidget(self.statusBadge)
        self.infoLayout.addLayout(self.rowTrangThai)
        self.outerLayout.addWidget(self.infoBanner)
        spacerItem14 = QtWidgets.QSpacerItem(0, 16, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.outerLayout.addItem(spacerItem14)
        self.btnSecondaryLayout = QtWidgets.QHBoxLayout()
        self.btnSecondaryLayout.setSpacing(12)
        self.btnSecondaryLayout.setObjectName("btnSecondaryLayout")
        self.btnDownload = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDownload.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnDownload.setStyleSheet("color:#0284C7; font-size:12.5px; font-weight:500;")
        self.btnDownload.setObjectName("btnDownload")
        self.btnSecondaryLayout.addWidget(self.btnDownload)
        self.btnShare = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnShare.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnShare.setStyleSheet("color:#0284C7; font-size:12.5px; font-weight:500;")
        self.btnShare.setObjectName("btnShare")
        self.btnSecondaryLayout.addWidget(self.btnShare)
        self.outerLayout.addLayout(self.btnSecondaryLayout)
        spacerItem15 = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.outerLayout.addItem(spacerItem15)
        self.btnHome = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnHome.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnHome.setAutoFillBackground(False)
        self.btnHome.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #0EA5E9, stop:1 #0284C7);\n"
"        border: none;\n"
"        border-radius: 12px;\n"
"        color: #ffffff;\n"
"        font-size: 15px;\n"
"        font-weight: bold;")
        self.btnHome.setObjectName("btnHome")
        self.outerLayout.addWidget(self.btnHome)
        QRPaymentDialog.setCentralWidget(self.centralwidget)

        self.retranslateUi(QRPaymentDialog)
        QtCore.QMetaObject.connectSlotsByName(QRPaymentDialog)

    def retranslateUi(self, QRPaymentDialog):
        _translate = QtCore.QCoreApplication.translate
        QRPaymentDialog.setWindowTitle(_translate("QRPaymentDialog", "Mua vé thành công"))
        self.iconCircle.setText(_translate("QRPaymentDialog", "✓"))
        self.titleLabel.setText(_translate("QRPaymentDialog", "Mua vé thành công!"))
        self.ticketCodeLabel.setText(_translate("QRPaymentDialog", "Mã vé: #MTR-2024-05-001"))
        self.qrLabel.setText(_translate("QRPaymentDialog", "[QR Code]"))
        self.qrHintLabel.setText(_translate("QRPaymentDialog", "Quét mã này tại ga để sử dụng vé"))
        self.lblTuyenKey.setStyleSheet(_translate("QRPaymentDialog", "color:#0288D1;font-size:13px;font-weight:500;"))
        self.lblTuyenKey.setText(_translate("QRPaymentDialog", "Tuyến"))
        self.lblTuyenVal.setStyleSheet(_translate("QRPaymentDialog", "color:#0A4D7A;font-size:13px;font-weight:600;"))
        self.lblTuyenVal.setText(_translate("QRPaymentDialog", "Tuyến 1"))
        self.divider1.setStyleSheet(_translate("QRPaymentDialog", "background-color:#B3E0F5;margin:6px 0;"))
        self.lblHTKey.setStyleSheet(_translate("QRPaymentDialog", "color:#0288D1;font-size:13px;font-weight:500;"))
        self.lblHTKey.setText(_translate("QRPaymentDialog", "Hành trình"))
        self.lblHTVal.setStyleSheet(_translate("QRPaymentDialog", "color:#0A4D7A;font-size:13px;font-weight:600;"))
        self.lblHTVal.setText(_translate("QRPaymentDialog", "Bến Thành → Văn Thánh"))
        self.divider2.setStyleSheet(_translate("QRPaymentDialog", "background-color:#B3E0F5;margin:6px 0;"))
        self.lblLVKey.setStyleSheet(_translate("QRPaymentDialog", "color:#0288D1;font-size:13px;font-weight:500;"))
        self.lblLVKey.setText(_translate("QRPaymentDialog", "Loại vé"))
        self.lblLVVal.setStyleSheet(_translate("QRPaymentDialog", "color:#0A4D7A;font-size:13px;font-weight:600;"))
        self.lblLVVal.setText(_translate("QRPaymentDialog", "Vé lượt"))
        self.divider3.setStyleSheet(_translate("QRPaymentDialog", "background-color:#B3E0F5;margin:6px 0;"))
        self.lblGVKey.setStyleSheet(_translate("QRPaymentDialog", "color:#0288D1;font-size:13px;font-weight:500;"))
        self.lblGVKey.setText(_translate("QRPaymentDialog", "Giá vé"))
        self.lblGVVal.setStyleSheet(_translate("QRPaymentDialog", "color:#0A4D7A;font-size:13px;font-weight:700;"))
        self.lblGVVal.setText(_translate("QRPaymentDialog", "12,000 VNĐ"))
        self.divider4.setStyleSheet(_translate("QRPaymentDialog", "background-color:#B3E0F5;margin:6px 0;"))
        self.lblNMKey.setStyleSheet(_translate("QRPaymentDialog", "color:#0288D1;font-size:13px;font-weight:500;"))
        self.lblNMKey.setText(_translate("QRPaymentDialog", "Ngày mua"))
        self.lblNMVal.setStyleSheet(_translate("QRPaymentDialog", "color:#0A4D7A;font-size:13px;font-weight:600;"))
        self.lblNMVal.setText(_translate("QRPaymentDialog", "24/05/2026"))
        self.divider5.setStyleSheet(_translate("QRPaymentDialog", "background-color:#B3E0F5;margin:6px 0;"))
        self.lblTTKey.setStyleSheet(_translate("QRPaymentDialog", "color:#0288D1;font-size:13px;font-weight:500;"))
        self.lblTTKey.setText(_translate("QRPaymentDialog", "Trạng thái"))
        self.statusBadge.setText(_translate("QRPaymentDialog", "Chưa sử dụng"))
        self.btnDownload.setText(_translate("QRPaymentDialog", "⬇  Tải về"))
        self.btnShare.setText(_translate("QRPaymentDialog", "⇆  Chia sẻ"))
        self.btnHome.setText(_translate("QRPaymentDialog", "Về trang chủ  ↗"))
