# Form implementation generated from reading ui file 'QuenMatKhau_Ver3.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ForgotPasswordWindow(object):
    def setupUi(self, ForgotPasswordWindow):
        ForgotPasswordWindow.setObjectName("ForgotPasswordWindow")
        ForgotPasswordWindow.resize(460, 680)
        ForgotPasswordWindow.setMinimumSize(QtCore.QSize(440, 660))
        ForgotPasswordWindow.setStyleSheet("\n"
"QWidget#centralwidget {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0.3, y2:1,\n"
"        stop:0 #0D1F3C, stop:0.4 #0A3060,\n"
"        stop:0.7 #0D4080, stop:1 #1A5FA8);\n"
"}\n"
"QFrame#form_card {\n"
"    background-color: rgba(255,255,255,0.97);\n"
"    border-radius: 22px;\n"
"    border: 1px solid rgba(255,255,255,0.15);\n"
"    border-bottom: 4px solid rgba(0,40,100,0.28);\n"
"}\n"
"QFrame#icon_outer {\n"
"    background: qlineargradient(x1:0,y1:0,x2:1,y2:1,\n"
"        stop:0 #1E90FF, stop:0.5 #0060D0, stop:1 #003A8C);\n"
"    border-radius: 20px;\n"
"    border-top: 2px solid rgba(255,255,255,0.28);\n"
"    border-left: 1px solid rgba(255,255,255,0.12);\n"
"    border-right: 1px solid rgba(0,0,0,0.25);\n"
"    border-bottom: 2px solid rgba(0,0,0,0.35);\n"
"}\n"
"QFrame#icon_inner {\n"
"    background: qlineargradient(x1:0,y1:0,x2:1,y2:1,\n"
"        stop:0 #2AA0FF, stop:1 #0070E0);\n"
"    border-radius: 13px;\n"
"    border-top: 1px solid rgba(255,255,255,0.20);\n"
"    border-bottom: 1px solid rgba(0,0,0,0.30);\n"
"}\n"
"QLabel#lbl_icon_key { color:#E0F2FE; font-size:22px; }\n"
"QLabel#lbl_title { color:#FFFFFF; font-size:21px; font-weight:700; }\n"
"QLabel#lbl_subtitle { color:rgba(148,213,252,0.85); font-size:11px; letter-spacing:1.2px; }\n"
"QFrame#step_dot_1 {\n"
"    background: qlineargradient(x1:0,y1:0,x2:1,y2:1,stop:0 #38BDF8,stop:1 #0284C7);\n"
"    border-radius: 11px;\n"
"    border: 2px solid rgba(255,255,255,0.35);\n"
"}\n"
"QFrame#step_dot_2 {\n"
"    background: rgba(255,255,255,0.15);\n"
"    border-radius: 11px;\n"
"    border: 2px solid rgba(148,213,252,0.35);\n"
"}\n"
"QLabel#lbl_step_num_1 { color:#FFFFFF; font-size:11px; font-weight:700; }\n"
"QLabel#lbl_step_num_2 { color:rgba(148,213,252,0.60); font-size:11px; font-weight:600; }\n"
"QFrame#step_line { background:rgba(148,213,252,0.30); max-height:2px; min-height:2px; }\n"
"QLabel#lbl_step_label_1 { color:#7DD3FC; font-size:10px; font-weight:600; }\n"
"QLabel#lbl_step_label_2 { color:rgba(148,213,252,0.45); font-size:10px; }\n"
"QLabel#lbl_field_user, QLabel#lbl_field_phone, QLabel#lbl_field_newpass {\n"
"    color:#0369A1; font-size:11px; font-weight:700; letter-spacing:0.8px;\n"
"}\n"
"QLineEdit#txt_username, QLineEdit#txt_phone, QLineEdit#txt_new_pass {\n"
"    background-color:#F0F9FF; border:1.5px solid #BAE6FD;\n"
"    border-radius:12px; padding:10px 14px;\n"
"    font-size:13px; color:#0C4A6E;\n"
"}\n"
"QLineEdit#txt_username:hover, QLineEdit#txt_phone:hover, QLineEdit#txt_new_pass:hover {\n"
"    border-color:#38BDF8; background-color:#E8F6FD;\n"
"}\n"
"QLineEdit#txt_username:focus, QLineEdit#txt_phone:focus, QLineEdit#txt_new_pass:focus {\n"
"    border-color:#0284C7; background-color:#FFFFFF;\n"
"}\n"
"QLineEdit#txt_username:disabled, QLineEdit#txt_phone:disabled {\n"
"    background-color:#EFF6FB; color:#94A8B8; border-color:#DCEEF8;\n"
"}\n"
"QPushButton#btn_action {\n"
"    background: qlineargradient(x1:0,y1:0,x2:1,y2:0,\n"
"        stop:0 #0284C7, stop:0.5 #0EA5E9, stop:1 #38BDF8);\n"
"    color:#FFFFFF; border:none; border-radius:13px;\n"
"    font-size:14px; font-weight:700;\n"
"    border-top:1px solid rgba(255,255,255,0.20);\n"
"}\n"
"QPushButton#btn_action:hover {\n"
"    background: qlineargradient(x1:0,y1:0,x2:1,y2:0,\n"
"        stop:0 #0369A1, stop:0.5 #0284C7, stop:1 #0EA5E9);\n"
"}\n"
"QPushButton#btn_action:pressed {\n"
"    background: qlineargradient(x1:0,y1:0,x2:1,y2:0,\n"
"        stop:0 #075985, stop:1 #0284C7);\n"
"}\n"
"QFrame#hint_banner {\n"
"    background:rgba(255,255,255,0.07);\n"
"    border-radius:12px;\n"
"    border:1px solid rgba(148,213,252,0.20);\n"
"    border-left:3px solid rgba(56,189,248,0.65);\n"
"}\n"
"QLabel#lbl_hint_icon { font-size:13px; }\n"
"QLabel#lbl_hint_text { color:rgba(186,230,253,0.78); font-size:11px; }\n"
"QFrame#pill_secure, QFrame#pill_support {\n"
"    background-color:rgba(255,255,255,0.09);\n"
"    border:1px solid rgba(148,213,252,0.22);\n"
"    border-radius:14px;\n"
"}\n"
"QLabel#lbl_pill_dot_s, QLabel#lbl_pill_dot_sp { color:#38BDF8; font-size:13px; }\n"
"QLabel#lbl_pill_secure, QLabel#lbl_pill_support { color:rgba(186,230,253,0.80); font-size:11px; }\n"
"QPushButton#btn_back {\n"
"    background:transparent; border:none;\n"
"    color:rgba(125,211,252,0.80); font-size:13px; font-weight:600;\n"
"}\n"
"QPushButton#btn_back:hover { color:#FFFFFF; }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=ForgotPasswordWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.root_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.root_layout.setContentsMargins(32, 26, 32, 22)
        self.root_layout.setSpacing(0)
        self.root_layout.setObjectName("root_layout")
        self.icon_row = QtWidgets.QHBoxLayout()
        self.icon_row.setObjectName("icon_row")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.icon_row.addItem(spacerItem)
        self.icon_outer = QtWidgets.QFrame(parent=self.centralwidget)
        self.icon_outer.setMinimumSize(QtCore.QSize(68, 68))
        self.icon_outer.setMaximumSize(QtCore.QSize(68, 68))
        self.icon_outer.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.icon_outer.setObjectName("icon_outer")
        self.icon_outer_layout = QtWidgets.QVBoxLayout(self.icon_outer)
        self.icon_outer_layout.setContentsMargins(8, 8, 8, 8)
        self.icon_outer_layout.setObjectName("icon_outer_layout")
        self.icon_inner = QtWidgets.QFrame(parent=self.icon_outer)
        self.icon_inner.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.icon_inner.setObjectName("icon_inner")
        self.icon_inner_layout = QtWidgets.QVBoxLayout(self.icon_inner)
        self.icon_inner_layout.setContentsMargins(0, 0, 0, 0)
        self.icon_inner_layout.setObjectName("icon_inner_layout")
        self.lbl_icon_key = QtWidgets.QLabel(parent=self.icon_inner)
        self.lbl_icon_key.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_icon_key.setObjectName("lbl_icon_key")
        self.icon_inner_layout.addWidget(self.lbl_icon_key)
        self.icon_outer_layout.addWidget(self.icon_inner)
        self.icon_row.addWidget(self.icon_outer)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.icon_row.addItem(spacerItem1)
        self.root_layout.addLayout(self.icon_row)
        spacerItem2 = QtWidgets.QSpacerItem(0, 12, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.root_layout.addItem(spacerItem2)
        self.lbl_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.root_layout.addWidget(self.lbl_title)
        spacerItem3 = QtWidgets.QSpacerItem(0, 4, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.root_layout.addItem(spacerItem3)
        self.lbl_subtitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_subtitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_subtitle.setObjectName("lbl_subtitle")
        self.root_layout.addWidget(self.lbl_subtitle)
        spacerItem4 = QtWidgets.QSpacerItem(0, 14, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.root_layout.addItem(spacerItem4)
        self.step_row = QtWidgets.QHBoxLayout()
        self.step_row.setObjectName("step_row")
        spacerItem5 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.step_row.addItem(spacerItem5)
        self.step1_col = QtWidgets.QVBoxLayout()
        self.step1_col.setSpacing(4)
        self.step1_col.setObjectName("step1_col")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setSpacing(0)
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem6 = QtWidgets.QSpacerItem(8, 8, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hboxlayout.addItem(spacerItem6)
        self.step_dot_1 = QtWidgets.QFrame(parent=self.centralwidget)
        self.step_dot_1.setMinimumSize(QtCore.QSize(24, 24))
        self.step_dot_1.setMaximumSize(QtCore.QSize(24, 24))
        self.step_dot_1.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.step_dot_1.setObjectName("step_dot_1")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.step_dot_1)
        self.vboxlayout.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.lbl_step_num_1 = QtWidgets.QLabel(parent=self.step_dot_1)
        self.lbl_step_num_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_step_num_1.setObjectName("lbl_step_num_1")
        self.vboxlayout.addWidget(self.lbl_step_num_1)
        self.hboxlayout.addWidget(self.step_dot_1)
        spacerItem7 = QtWidgets.QSpacerItem(8, 8, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hboxlayout.addItem(spacerItem7)
        self.step1_col.addLayout(self.hboxlayout)
        self.lbl_step_label_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_step_label_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_step_label_1.setObjectName("lbl_step_label_1")
        self.step1_col.addWidget(self.lbl_step_label_1)
        self.step_row.addLayout(self.step1_col)
        self.vboxlayout1 = QtWidgets.QVBoxLayout()
        self.vboxlayout1.setSpacing(0)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.step_line = QtWidgets.QFrame(parent=self.centralwidget)
        self.step_line.setMinimumSize(QtCore.QSize(70, 2))
        self.step_line.setMaximumSize(QtCore.QSize(70, 2))
        self.step_line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.step_line.setObjectName("step_line")
        self.vboxlayout1.addWidget(self.step_line)
        spacerItem8 = QtWidgets.QSpacerItem(0, 16, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.vboxlayout1.addItem(spacerItem8)
        self.step_row.addLayout(self.vboxlayout1)
        self.step2_col = QtWidgets.QVBoxLayout()
        self.step2_col.setSpacing(4)
        self.step2_col.setObjectName("step2_col")
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setSpacing(0)
        self.hboxlayout1.setObjectName("hboxlayout1")
        spacerItem9 = QtWidgets.QSpacerItem(8, 8, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hboxlayout1.addItem(spacerItem9)
        self.step_dot_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.step_dot_2.setMinimumSize(QtCore.QSize(24, 24))
        self.step_dot_2.setMaximumSize(QtCore.QSize(24, 24))
        self.step_dot_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.step_dot_2.setObjectName("step_dot_2")
        self.vboxlayout2 = QtWidgets.QVBoxLayout(self.step_dot_2)
        self.vboxlayout2.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.lbl_step_num_2 = QtWidgets.QLabel(parent=self.step_dot_2)
        self.lbl_step_num_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_step_num_2.setObjectName("lbl_step_num_2")
        self.vboxlayout2.addWidget(self.lbl_step_num_2)
        self.hboxlayout1.addWidget(self.step_dot_2)
        spacerItem10 = QtWidgets.QSpacerItem(8, 8, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hboxlayout1.addItem(spacerItem10)
        self.step2_col.addLayout(self.hboxlayout1)
        self.lbl_step_label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_step_label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_step_label_2.setObjectName("lbl_step_label_2")
        self.step2_col.addWidget(self.lbl_step_label_2)
        self.step_row.addLayout(self.step2_col)
        spacerItem11 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.step_row.addItem(spacerItem11)
        self.root_layout.addLayout(self.step_row)
        spacerItem12 = QtWidgets.QSpacerItem(0, 16, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.root_layout.addItem(spacerItem12)
        self.form_card = QtWidgets.QFrame(parent=self.centralwidget)
        self.form_card.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.form_card.setObjectName("form_card")
        self.form_layout = QtWidgets.QVBoxLayout(self.form_card)
        self.form_layout.setContentsMargins(24, 20, 24, 20)
        self.form_layout.setSpacing(8)
        self.form_layout.setObjectName("form_layout")
        self.lbl_field_user = QtWidgets.QLabel(parent=self.form_card)
        self.lbl_field_user.setObjectName("lbl_field_user")
        self.form_layout.addWidget(self.lbl_field_user)
        self.txt_username = QtWidgets.QLineEdit(parent=self.form_card)
        self.txt_username.setMinimumSize(QtCore.QSize(0, 44))
        self.txt_username.setClearButtonEnabled(True)
        self.txt_username.setObjectName("txt_username")
        self.form_layout.addWidget(self.txt_username)
        spacerItem13 = QtWidgets.QSpacerItem(0, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.form_layout.addItem(spacerItem13)
        self.lbl_field_phone = QtWidgets.QLabel(parent=self.form_card)
        self.lbl_field_phone.setObjectName("lbl_field_phone")
        self.form_layout.addWidget(self.lbl_field_phone)
        self.txt_phone = QtWidgets.QLineEdit(parent=self.form_card)
        self.txt_phone.setMinimumSize(QtCore.QSize(0, 44))
        self.txt_phone.setClearButtonEnabled(True)
        self.txt_phone.setObjectName("txt_phone")
        self.form_layout.addWidget(self.txt_phone)
        spacerItem14 = QtWidgets.QSpacerItem(0, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.form_layout.addItem(spacerItem14)
        self.lbl_field_newpass = QtWidgets.QLabel(parent=self.form_card)
        self.lbl_field_newpass.setObjectName("lbl_field_newpass")
        self.form_layout.addWidget(self.lbl_field_newpass)
        self.txt_new_pass = QtWidgets.QLineEdit(parent=self.form_card)
        self.txt_new_pass.setMinimumSize(QtCore.QSize(0, 44))
        self.txt_new_pass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_new_pass.setObjectName("txt_new_pass")
        self.form_layout.addWidget(self.txt_new_pass)
        spacerItem15 = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.form_layout.addItem(spacerItem15)
        self.btn_action = QtWidgets.QPushButton(parent=self.form_card)
        self.btn_action.setMinimumSize(QtCore.QSize(0, 48))
        self.btn_action.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_action.setDefault(True)
        self.btn_action.setObjectName("btn_action")
        self.form_layout.addWidget(self.btn_action)
        self.root_layout.addWidget(self.form_card)
        spacerItem16 = QtWidgets.QSpacerItem(0, 12, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.root_layout.addItem(spacerItem16)
        self.hint_banner = QtWidgets.QFrame(parent=self.centralwidget)
        self.hint_banner.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.hint_banner.setObjectName("hint_banner")
        self.hint_layout = QtWidgets.QHBoxLayout(self.hint_banner)
        self.hint_layout.setContentsMargins(14, 10, 14, 10)
        self.hint_layout.setSpacing(10)
        self.hint_layout.setObjectName("hint_layout")
        self.lbl_hint_icon = QtWidgets.QLabel(parent=self.hint_banner)
        self.lbl_hint_icon.setAlignment(QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_hint_icon.setObjectName("lbl_hint_icon")
        self.hint_layout.addWidget(self.lbl_hint_icon)
        self.lbl_hint_text = QtWidgets.QLabel(parent=self.hint_banner)
        self.lbl_hint_text.setWordWrap(True)
        self.lbl_hint_text.setObjectName("lbl_hint_text")
        self.hint_layout.addWidget(self.lbl_hint_text)
        self.root_layout.addWidget(self.hint_banner)
        spacerItem17 = QtWidgets.QSpacerItem(0, 12, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.root_layout.addItem(spacerItem17)
        self.pills_row = QtWidgets.QHBoxLayout()
        self.pills_row.setObjectName("pills_row")
        spacerItem18 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.pills_row.addItem(spacerItem18)
        self.pill_secure = QtWidgets.QFrame(parent=self.centralwidget)
        self.pill_secure.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.pill_secure.setObjectName("pill_secure")
        self.pill_secure_layout = QtWidgets.QHBoxLayout(self.pill_secure)
        self.pill_secure_layout.setContentsMargins(10, 5, 10, 5)
        self.pill_secure_layout.setSpacing(6)
        self.pill_secure_layout.setObjectName("pill_secure_layout")
        self.lbl_pill_dot_s = QtWidgets.QLabel(parent=self.pill_secure)
        self.lbl_pill_dot_s.setObjectName("lbl_pill_dot_s")
        self.pill_secure_layout.addWidget(self.lbl_pill_dot_s)
        self.lbl_pill_secure = QtWidgets.QLabel(parent=self.pill_secure)
        self.lbl_pill_secure.setObjectName("lbl_pill_secure")
        self.pill_secure_layout.addWidget(self.lbl_pill_secure)
        self.pills_row.addWidget(self.pill_secure)
        spacerItem19 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.pills_row.addItem(spacerItem19)
        self.pill_support = QtWidgets.QFrame(parent=self.centralwidget)
        self.pill_support.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.pill_support.setObjectName("pill_support")
        self.pill_support_layout = QtWidgets.QHBoxLayout(self.pill_support)
        self.pill_support_layout.setContentsMargins(10, 5, 10, 5)
        self.pill_support_layout.setSpacing(6)
        self.pill_support_layout.setObjectName("pill_support_layout")
        self.lbl_pill_dot_sp = QtWidgets.QLabel(parent=self.pill_support)
        self.lbl_pill_dot_sp.setObjectName("lbl_pill_dot_sp")
        self.pill_support_layout.addWidget(self.lbl_pill_dot_sp)
        self.lbl_pill_support = QtWidgets.QLabel(parent=self.pill_support)
        self.lbl_pill_support.setObjectName("lbl_pill_support")
        self.pill_support_layout.addWidget(self.lbl_pill_support)
        self.pills_row.addWidget(self.pill_support)
        spacerItem20 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.pills_row.addItem(spacerItem20)
        self.root_layout.addLayout(self.pills_row)
        spacerItem21 = QtWidgets.QSpacerItem(0, 12, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.root_layout.addItem(spacerItem21)
        self.back_row = QtWidgets.QHBoxLayout()
        self.back_row.setObjectName("back_row")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.back_row.addItem(spacerItem22)
        self.btn_back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_back.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_back.setFlat(True)
        self.btn_back.setObjectName("btn_back")
        self.back_row.addWidget(self.btn_back)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.back_row.addItem(spacerItem23)
        self.root_layout.addLayout(self.back_row)
        spacerItem24 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.root_layout.addItem(spacerItem24)
        ForgotPasswordWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ForgotPasswordWindow)
        QtCore.QMetaObject.connectSlotsByName(ForgotPasswordWindow)
        ForgotPasswordWindow.setTabOrder(self.txt_username, self.txt_phone)
        ForgotPasswordWindow.setTabOrder(self.txt_phone, self.txt_new_pass)
        ForgotPasswordWindow.setTabOrder(self.txt_new_pass, self.btn_action)
        ForgotPasswordWindow.setTabOrder(self.btn_action, self.btn_back)

    def retranslateUi(self, ForgotPasswordWindow):
        _translate = QtCore.QCoreApplication.translate
        ForgotPasswordWindow.setWindowTitle(_translate("ForgotPasswordWindow", "Metro Ticket System – Khôi phục mật khẩu"))
        self.lbl_icon_key.setText(_translate("ForgotPasswordWindow", "🔑"))
        self.lbl_title.setText(_translate("ForgotPasswordWindow", "Khôi phục mật khẩu"))
        self.lbl_subtitle.setText(_translate("ForgotPasswordWindow", "XÁC THỰC  ·  ĐỔI MẬT KHẨU"))
        self.lbl_step_num_1.setText(_translate("ForgotPasswordWindow", "1"))
        self.lbl_step_label_1.setText(_translate("ForgotPasswordWindow", "Xác thực"))
        self.lbl_step_num_2.setText(_translate("ForgotPasswordWindow", "2"))
        self.lbl_step_label_2.setText(_translate("ForgotPasswordWindow", "Đổi mật khẩu"))
        self.lbl_field_user.setText(_translate("ForgotPasswordWindow", "TÊN TÀI KHOẢN"))
        self.txt_username.setPlaceholderText(_translate("ForgotPasswordWindow", "Nhập tên tài khoản cần lấy lại..."))
        self.lbl_field_phone.setText(_translate("ForgotPasswordWindow", "SỐ ĐIỆN THOẠI ĐĂNG KÝ"))
        self.txt_phone.setPlaceholderText(_translate("ForgotPasswordWindow", "Nhập số điện thoại đã đăng ký..."))
        self.lbl_field_newpass.setText(_translate("ForgotPasswordWindow", "MẬT KHẨU MỚI"))
        self.txt_new_pass.setPlaceholderText(_translate("ForgotPasswordWindow", "Nhập mật khẩu mới..."))
        self.btn_action.setText(_translate("ForgotPasswordWindow", "Xác thực thông tin  🔍"))
        self.lbl_hint_icon.setText(_translate("ForgotPasswordWindow", "💡"))
        self.lbl_hint_text.setText(_translate("ForgotPasswordWindow", "Dùng đúng Username và SĐT đã đăng ký để xác thực danh tính."))
        self.lbl_pill_dot_s.setText(_translate("ForgotPasswordWindow", "🔒"))
        self.lbl_pill_secure.setText(_translate("ForgotPasswordWindow", "Kết nối bảo mật"))
        self.lbl_pill_dot_sp.setText(_translate("ForgotPasswordWindow", "🛡️"))
        self.lbl_pill_support.setText(_translate("ForgotPasswordWindow", "Dữ liệu mã hóa"))
        self.btn_back.setText(_translate("ForgotPasswordWindow", "←  Quay lại Đăng nhập"))
