# Form implementation generated from reading ui file 'Thanhtoan.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MetroBookingForm(object):
    def setupUi(self, MetroBookingForm):
        MetroBookingForm.setObjectName("MetroBookingForm")
        MetroBookingForm.resize(436, 853)
        MetroBookingForm.setStyleSheet("\n"
"    /* Định hình giao diện tổng thể theo thiết kế Sky Blue */\n"
"    QWidget#centralwidget {\n"
"        background-color: #F0F9FF;\n"
"    }\n"
"\n"
"    QLabel {\n"
"        font-family: \'Segoe UI\', system-ui, sans-serif;\n"
"    }\n"
"\n"
"    /* Giao diện Thẻ (Card) */\n"
"    QFrame#cardJourney, QFrame#cardSummary {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #E0F2FE;\n"
"        border-radius: 16px;\n"
"    }\n"
"\n"
"    /* Tiêu đề Thẻ */\n"
"    QLabel#lblJourneyTitle {\n"
"        font-size: 15px;\n"
"        font-weight: bold;\n"
"        color: #0C4A6E;\n"
"    }\n"
"\n"
"    /* Nhãn các trường nhập liệu */\n"
"    QLabel.form-label {\n"
"        font-size: 12px;\n"
"        color: #0284C7;\n"
"        font-weight: 600;\n"
"    }\n"
"\n"
"    /* Hộp chọn Combo Box */\n"
"    QComboBox {\n"
"        padding: 8px 12px;\n"
"        border: 1px solid #BAE6FD;\n"
"        border-radius: 10px;\n"
"        font-size: 13px;\n"
"        color: #0C4A6E;\n"
"        background-color: #F0F9FF;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"        subcontrol-origin: padding;\n"
"        subcontrol-position: top right;\n"
"        width: 25px;\n"
"    }\n"
"\n"
"    /* Thẻ Loại Vé (Ticket Grid Item) */\n"
"    QFrame.ticket-card {\n"
"        border: 1.5px solid #E0F2FE;\n"
"        border-radius: 12px;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QFrame.ticket-card:hover {\n"
"        border-color: #7DD3FC;\n"
"        background-color: #F0F9FF;\n"
"    }\n"
"    /* Vé đang chọn mặc định */\n"
"    QFrame#frameTicket1 {\n"
"        border-color: #0EA5E9;\n"
"        background-color: #E0F2FE;\n"
"    }\n"
"\n"
"    /* Nút Tăng/Giảm số lượng */\n"
"    QPushButton.qty-btn {\n"
"        width: 30px;\n"
"        height: 30px;\n"
"        border-radius: 8px;\n"
"        border: 1px solid #BAE6FD;\n"
"        background-color: #F0F9FF;\n"
"        color: #0284C7;\n"
"        font-size: 16px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton.qty-btn:hover {\n"
"        background-color: #BAE6FD;\n"
"        border-color: #0EA5E9;\n"
"    }\n"
"\n"
"    /* Ví tiền và Số dư */\n"
"    QFrame#balanceBox {\n"
"        background-color: #E0F2FE;\n"
"        border-radius: 9px;\n"
"    }\n"
"\n"
"    /* Nút Thanh Toán */\n"
"    QPushButton#btnPay {\n"
"        background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #0EA5E9, stop:1 #0284C7);\n"
"        border: none;\n"
"        border-radius: 12px;\n"
"        color: #ffffff;\n"
"        font-size: 15px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton#btnPay:hover {\n"
"        background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #38BDF8, stop:1 #0284C7);\n"
"    }\n"
"\n"
"    /* Nút Back (góc trái, cùng hàng với tiêu đề trang) */\n"
"    QPushButton#btnBack {\n"
"        background-color: transparent;\n"
"        border: none;\n"
"        color: #0284C7;\n"
"        font-size: 20px;\n"
"        font-weight: bold;\n"
"        border-radius: 8px;\n"
"    }\n"
"    QPushButton#btnBack:hover {\n"
"        background-color: #E0F2FE;\n"
"    }\n"
"    QPushButton#btnBack:pressed {\n"
"        background-color: #BAE6FD;\n"
"    }\n"
"\n"
"    /* Tiêu đề trang đặt vé, đặt cùng hàng với nút Back */\n"
"    QLabel#lblPageTitle {\n"
"        color: #0C4A6E;\n"
"        font-size: 13px;\n"
"        font-weight: bold;\n"
"    }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=MetroBookingForm)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(14, 8, 14, 14)
        self.mainLayout.setSpacing(8)
        self.mainLayout.setObjectName("mainLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setSpacing(8)
        self.headerLayout.setObjectName("headerLayout")
        self.btnBack = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnBack.setMinimumSize(QtCore.QSize(26, 26))
        self.btnBack.setMaximumSize(QtCore.QSize(26, 26))
        self.btnBack.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnBack.setObjectName("btnBack")
        self.headerLayout.addWidget(self.btnBack)
        self.lblPageTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPageTitle.setObjectName("lblPageTitle")
        self.headerLayout.addWidget(self.lblPageTitle)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.mainLayout.addLayout(self.headerLayout)
        self.cardJourney = QtWidgets.QFrame(parent=self.centralwidget)
        self.cardJourney.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.cardJourney.setObjectName("cardJourney")
        self.journeyLayout = QtWidgets.QVBoxLayout(self.cardJourney)
        self.journeyLayout.setContentsMargins(16, 16, 16, 16)
        self.journeyLayout.setSpacing(10)
        self.journeyLayout.setObjectName("journeyLayout")
        self.stepperLayout = QtWidgets.QHBoxLayout()
        self.stepperLayout.setSpacing(4)
        self.stepperLayout.setObjectName("stepperLayout")
        self.step1Num = QtWidgets.QLabel(parent=self.cardJourney)
        self.step1Num.setMinimumSize(QtCore.QSize(28, 28))
        self.step1Num.setMaximumSize(QtCore.QSize(28, 28))
        self.step1Num.setStyleSheet("background:#0EA5E9; color:#fff; border-radius:14px; font-weight:bold; font-size:13px;")
        self.step1Num.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.step1Num.setObjectName("step1Num")
        self.stepperLayout.addWidget(self.step1Num)
        self.step1Label = QtWidgets.QLabel(parent=self.cardJourney)
        self.step1Label.setStyleSheet("color:#0369A1; font-weight:600; font-size:12px;")
        self.step1Label.setObjectName("step1Label")
        self.stepperLayout.addWidget(self.step1Label)
        self.line1 = QtWidgets.QFrame(parent=self.cardJourney)
        self.line1.setStyleSheet("color: #BAE6FD;")
        self.line1.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line1.setObjectName("line1")
        self.stepperLayout.addWidget(self.line1)
        self.step2Num = QtWidgets.QLabel(parent=self.cardJourney)
        self.step2Num.setMinimumSize(QtCore.QSize(28, 28))
        self.step2Num.setMaximumSize(QtCore.QSize(28, 28))
        self.step2Num.setStyleSheet("background:#fff; border:1.5px solid #BAE6FD; color:#7DD3FC; border-radius:14px; font-size:13px;")
        self.step2Num.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.step2Num.setObjectName("step2Num")
        self.stepperLayout.addWidget(self.step2Num)
        self.step2Label = QtWidgets.QLabel(parent=self.cardJourney)
        self.step2Label.setStyleSheet("color:#7DD3FC; font-size:12px;")
        self.step2Label.setObjectName("step2Label")
        self.stepperLayout.addWidget(self.step2Label)
        self.line2 = QtWidgets.QFrame(parent=self.cardJourney)
        self.line2.setStyleSheet("color: #BAE6FD;")
        self.line2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line2.setObjectName("line2")
        self.stepperLayout.addWidget(self.line2)
        self.step3Num = QtWidgets.QLabel(parent=self.cardJourney)
        self.step3Num.setMinimumSize(QtCore.QSize(28, 28))
        self.step3Num.setMaximumSize(QtCore.QSize(28, 28))
        self.step3Num.setStyleSheet("background:#fff; border:1.5px solid #BAE6FD; color:#7DD3FC; border-radius:14px; font-size:13px;")
        self.step3Num.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.step3Num.setObjectName("step3Num")
        self.stepperLayout.addWidget(self.step3Num)
        self.label = QtWidgets.QLabel(parent=self.cardJourney)
        self.label.setStyleSheet("color:#7DD3FC; font-size:12px;")
        self.label.setObjectName("label")
        self.stepperLayout.addWidget(self.label)
        self.journeyLayout.addLayout(self.stepperLayout)
        self.lblJourneyTitle = QtWidgets.QLabel(parent=self.cardJourney)
        self.lblJourneyTitle.setObjectName("lblJourneyTitle")
        self.journeyLayout.addWidget(self.lblJourneyTitle)
        self.lblLine = QtWidgets.QLabel(parent=self.cardJourney)
        self.lblLine.setObjectName("lblLine")
        self.journeyLayout.addWidget(self.lblLine)
        self.comboLine = QtWidgets.QComboBox(parent=self.cardJourney)
        self.comboLine.setObjectName("comboLine")
        self.comboLine.addItem("")
        self.comboLine.addItem("")
        self.comboLine.addItem("")
        self.journeyLayout.addWidget(self.comboLine)
        self.lblFrom = QtWidgets.QLabel(parent=self.cardJourney)
        self.lblFrom.setObjectName("lblFrom")
        self.journeyLayout.addWidget(self.lblFrom)
        self.comboFrom = QtWidgets.QComboBox(parent=self.cardJourney)
        self.comboFrom.setObjectName("comboFrom")
        self.comboFrom.addItem("")
        self.comboFrom.addItem("")
        self.comboFrom.addItem("")
        self.comboFrom.addItem("")
        self.comboFrom.addItem("")
        self.comboFrom.addItem("")
        self.journeyLayout.addWidget(self.comboFrom)
        self.lblTo = QtWidgets.QLabel(parent=self.cardJourney)
        self.lblTo.setObjectName("lblTo")
        self.journeyLayout.addWidget(self.lblTo)
        self.comboTo = QtWidgets.QComboBox(parent=self.cardJourney)
        self.comboTo.setObjectName("comboTo")
        self.comboTo.addItem("")
        self.comboTo.addItem("")
        self.comboTo.addItem("")
        self.comboTo.addItem("")
        self.comboTo.addItem("")
        self.journeyLayout.addWidget(self.comboTo)
        self.lblTicketType = QtWidgets.QLabel(parent=self.cardJourney)
        self.lblTicketType.setObjectName("lblTicketType")
        self.journeyLayout.addWidget(self.lblTicketType)
        self.gridTickets = QtWidgets.QGridLayout()
        self.gridTickets.setSpacing(8)
        self.gridTickets.setObjectName("gridTickets")
        self.frameTicket1 = QtWidgets.QFrame(parent=self.cardJourney)
        self.frameTicket1.setObjectName("frameTicket1")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.frameTicket1)
        self.vboxlayout.setObjectName("vboxlayout")
        self.t1_a = QtWidgets.QLabel(parent=self.frameTicket1)
        self.t1_a.setObjectName("t1_a")
        self.vboxlayout.addWidget(self.t1_a)
        self.t1_b = QtWidgets.QLabel(parent=self.frameTicket1)
        self.t1_b.setObjectName("t1_b")
        self.vboxlayout.addWidget(self.t1_b)
        self.t1_c = QtWidgets.QLabel(parent=self.frameTicket1)
        self.t1_c.setObjectName("t1_c")
        self.vboxlayout.addWidget(self.t1_c)
        self.gridTickets.addWidget(self.frameTicket1, 0, 0, 1, 1)
        self.frameTicket2 = QtWidgets.QFrame(parent=self.cardJourney)
        self.frameTicket2.setObjectName("frameTicket2")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.frameTicket2)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.t2_a = QtWidgets.QLabel(parent=self.frameTicket2)
        self.t2_a.setObjectName("t2_a")
        self.vboxlayout1.addWidget(self.t2_a)
        self.t2_b = QtWidgets.QLabel(parent=self.frameTicket2)
        self.t2_b.setObjectName("t2_b")
        self.vboxlayout1.addWidget(self.t2_b)
        self.t2_c = QtWidgets.QLabel(parent=self.frameTicket2)
        self.t2_c.setObjectName("t2_c")
        self.vboxlayout1.addWidget(self.t2_c)
        self.gridTickets.addWidget(self.frameTicket2, 0, 1, 1, 1)
        self.frameTicket3 = QtWidgets.QFrame(parent=self.cardJourney)
        self.frameTicket3.setObjectName("frameTicket3")
        self.vboxlayout2 = QtWidgets.QVBoxLayout(self.frameTicket3)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.t3_a = QtWidgets.QLabel(parent=self.frameTicket3)
        self.t3_a.setObjectName("t3_a")
        self.vboxlayout2.addWidget(self.t3_a)
        self.t3_b = QtWidgets.QLabel(parent=self.frameTicket3)
        self.t3_b.setObjectName("t3_b")
        self.vboxlayout2.addWidget(self.t3_b)
        self.t3_c = QtWidgets.QLabel(parent=self.frameTicket3)
        self.t3_c.setObjectName("t3_c")
        self.vboxlayout2.addWidget(self.t3_c)
        self.gridTickets.addWidget(self.frameTicket3, 1, 0, 1, 1)
        self.frameTicket4 = QtWidgets.QFrame(parent=self.cardJourney)
        self.frameTicket4.setObjectName("frameTicket4")
        self.vboxlayout3 = QtWidgets.QVBoxLayout(self.frameTicket4)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.t4_a = QtWidgets.QLabel(parent=self.frameTicket4)
        self.t4_a.setObjectName("t4_a")
        self.vboxlayout3.addWidget(self.t4_a)
        self.t4_b = QtWidgets.QLabel(parent=self.frameTicket4)
        self.t4_b.setObjectName("t4_b")
        self.vboxlayout3.addWidget(self.t4_b)
        self.t4_c = QtWidgets.QLabel(parent=self.frameTicket4)
        self.t4_c.setObjectName("t4_c")
        self.vboxlayout3.addWidget(self.t4_c)
        self.gridTickets.addWidget(self.frameTicket4, 1, 1, 1, 1)
        self.journeyLayout.addLayout(self.gridTickets)
        self.mainLayout.addWidget(self.cardJourney)
        self.cardSummary = QtWidgets.QFrame(parent=self.centralwidget)
        self.cardSummary.setObjectName("cardSummary")
        self.summaryLayout = QtWidgets.QVBoxLayout(self.cardSummary)
        self.summaryLayout.setSpacing(8)
        self.summaryLayout.setObjectName("summaryLayout")
        self.rowSumType = QtWidgets.QHBoxLayout()
        self.rowSumType.setObjectName("rowSumType")
        self.s1 = QtWidgets.QLabel(parent=self.cardSummary)
        self.s1.setObjectName("s1")
        self.rowSumType.addWidget(self.s1)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.rowSumType.addItem(spacerItem1)
        self.sumType = QtWidgets.QLabel(parent=self.cardSummary)
        self.sumType.setObjectName("sumType")
        self.rowSumType.addWidget(self.sumType)
        self.summaryLayout.addLayout(self.rowSumType)
        self.lineDivider = QtWidgets.QFrame(parent=self.cardSummary)
        self.lineDivider.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.lineDivider.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lineDivider.setObjectName("lineDivider")
        self.summaryLayout.addWidget(self.lineDivider)
        self.rowTotal = QtWidgets.QHBoxLayout()
        self.rowTotal.setObjectName("rowTotal")
        self.s3 = QtWidgets.QLabel(parent=self.cardSummary)
        self.s3.setObjectName("s3")
        self.rowTotal.addWidget(self.s3)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.rowTotal.addItem(spacerItem2)
        self.sumTotal = QtWidgets.QLabel(parent=self.cardSummary)
        self.sumTotal.setObjectName("sumTotal")
        self.rowTotal.addWidget(self.sumTotal)
        self.summaryLayout.addLayout(self.rowTotal)
        self.mainLayout.addWidget(self.cardSummary)
        self.balanceBox = QtWidgets.QFrame(parent=self.centralwidget)
        self.balanceBox.setMinimumSize(QtCore.QSize(0, 38))
        self.balanceBox.setObjectName("balanceBox")
        self.balanceLayout = QtWidgets.QHBoxLayout(self.balanceBox)
        self.balanceLayout.setContentsMargins(12, 6, 12, 6)
        self.balanceLayout.setObjectName("balanceLayout")
        self.lblBalance = QtWidgets.QLabel(parent=self.balanceBox)
        self.lblBalance.setObjectName("lblBalance")
        self.balanceLayout.addWidget(self.lblBalance)
        self.mainLayout.addWidget(self.balanceBox)
        self.btnPay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnPay.setMinimumSize(QtCore.QSize(0, 46))
        self.btnPay.setObjectName("btnPay")
        self.mainLayout.addWidget(self.btnPay)
        MetroBookingForm.setCentralWidget(self.centralwidget)

        self.retranslateUi(MetroBookingForm)
        QtCore.QMetaObject.connectSlotsByName(MetroBookingForm)

    def retranslateUi(self, MetroBookingForm):
        _translate = QtCore.QCoreApplication.translate
        MetroBookingForm.setWindowTitle(_translate("MetroBookingForm", "Đặt Vé Metro"))
        self.btnBack.setText(_translate("MetroBookingForm", "←"))
        self.lblPageTitle.setText(_translate("MetroBookingForm", "🎫 Đặt vé Metro"))
        self.step1Num.setText(_translate("MetroBookingForm", "1"))
        self.step1Label.setText(_translate("MetroBookingForm", "Chọn tuyến"))
        self.step2Num.setText(_translate("MetroBookingForm", "2"))
        self.step2Label.setText(_translate("MetroBookingForm", "Chọn vé"))
        self.step3Num.setText(_translate("MetroBookingForm", "3"))
        self.label.setText(_translate("MetroBookingForm", "Thanh Toán"))
        self.lblJourneyTitle.setText(_translate("MetroBookingForm", "📍 Thông tin hành trình"))
        self.lblLine.setText(_translate("MetroBookingForm", "Chọn tuyến"))
        self.lblLine.setProperty("class", _translate("MetroBookingForm", "form-label"))
        self.comboLine.setItemText(0, _translate("MetroBookingForm", "Tuyến 1: Bến Thành – Suối Tiên"))
        self.comboLine.setItemText(1, _translate("MetroBookingForm", "Tuyến 2: Bến Thành – Tham Lương"))
        self.comboLine.setItemText(2, _translate("MetroBookingForm", "Tuyến 3: Bến Thành – Tân Kiên"))
        self.lblFrom.setText(_translate("MetroBookingForm", "Ga đi"))
        self.lblFrom.setProperty("class", _translate("MetroBookingForm", "form-label"))
        self.comboFrom.setItemText(0, _translate("MetroBookingForm", "Bến Thành"))
        self.comboFrom.setItemText(1, _translate("MetroBookingForm", "Nhà hát Thành phố"))
        self.comboFrom.setItemText(2, _translate("MetroBookingForm", "Ba Son"))
        self.comboFrom.setItemText(3, _translate("MetroBookingForm", "Văn Thánh"))
        self.comboFrom.setItemText(4, _translate("MetroBookingForm", "Tân Cảng"))
        self.comboFrom.setItemText(5, _translate("MetroBookingForm", "Thảo Điền"))
        self.lblTo.setText(_translate("MetroBookingForm", "Ga đến"))
        self.lblTo.setProperty("class", _translate("MetroBookingForm", "form-label"))
        self.comboTo.setItemText(0, _translate("MetroBookingForm", "Văn Thánh"))
        self.comboTo.setItemText(1, _translate("MetroBookingForm", "Bến Thành"))
        self.comboTo.setItemText(2, _translate("MetroBookingForm", "Nhà hát Thành phố"))
        self.comboTo.setItemText(3, _translate("MetroBookingForm", "Ba Son"))
        self.comboTo.setItemText(4, _translate("MetroBookingForm", "Tân Cảng"))
        self.lblTicketType.setText(_translate("MetroBookingForm", "Loại vé"))
        self.lblTicketType.setProperty("class", _translate("MetroBookingForm", "form-label"))
        self.frameTicket1.setProperty("class", _translate("MetroBookingForm", "ticket-card"))
        self.t1_a.setStyleSheet(_translate("MetroBookingForm", "color:#0369A1;font-weight:600;font-size:12px;"))
        self.t1_a.setText(_translate("MetroBookingForm", "Vé lượt"))
        self.t1_b.setStyleSheet(_translate("MetroBookingForm", "color:#0369A1;font-weight:bold;font-size:15px;"))
        self.t1_b.setText(_translate("MetroBookingForm", "12.000 VNĐ"))
        self.t1_c.setStyleSheet(_translate("MetroBookingForm", "color:#0284C7;font-size:11px;"))
        self.t1_c.setText(_translate("MetroBookingForm", "1 chuyến đi"))
        self.frameTicket2.setProperty("class", _translate("MetroBookingForm", "ticket-card"))
        self.t2_a.setStyleSheet(_translate("MetroBookingForm", "color:#0284C7;font-weight:600;font-size:12px;"))
        self.t2_a.setText(_translate("MetroBookingForm", "Vé ngày"))
        self.t2_b.setStyleSheet(_translate("MetroBookingForm", "color:#0C4A6E;font-weight:bold;font-size:15px;"))
        self.t2_b.setText(_translate("MetroBookingForm", "40.000 VNĐ"))
        self.t2_c.setStyleSheet(_translate("MetroBookingForm", "color:#38BDF8;font-size:11px;"))
        self.t2_c.setText(_translate("MetroBookingForm", "1 ngày"))
        self.frameTicket3.setProperty("class", _translate("MetroBookingForm", "ticket-card"))
        self.t3_a.setStyleSheet(_translate("MetroBookingForm", "color:#0284C7;font-weight:600;font-size:12px;"))
        self.t3_a.setText(_translate("MetroBookingForm", "Vé 1 tháng"))
        self.t3_b.setStyleSheet(_translate("MetroBookingForm", "color:#0C4A6E;font-weight:bold;font-size:15px;"))
        self.t3_b.setText(_translate("MetroBookingForm", "300.000 VNĐ"))
        self.t3_c.setStyleSheet(_translate("MetroBookingForm", "color:#38BDF8;font-size:11px;"))
        self.t3_c.setText(_translate("MetroBookingForm", "30 ngày"))
        self.frameTicket4.setProperty("class", _translate("MetroBookingForm", "ticket-card"))
        self.t4_a.setStyleSheet(_translate("MetroBookingForm", "color:#0284C7;font-weight:600;font-size:12px;"))
        self.t4_a.setText(_translate("MetroBookingForm", "Vé 3 tháng"))
        self.t4_b.setStyleSheet(_translate("MetroBookingForm", "color:#0C4A6E;font-weight:bold;font-size:15px;"))
        self.t4_b.setText(_translate("MetroBookingForm", "700.000 VNĐ"))
        self.t4_c.setStyleSheet(_translate("MetroBookingForm", "color:#38BDF8;font-size:11px;"))
        self.t4_c.setText(_translate("MetroBookingForm", "90 ngày"))
        self.s1.setStyleSheet(_translate("MetroBookingForm", "color:#38BDF8; font-size:13px;"))
        self.s1.setText(_translate("MetroBookingForm", "Loại vé"))
        self.sumType.setStyleSheet(_translate("MetroBookingForm", "color:#0369A1; font-weight:500; font-size:13px;"))
        self.sumType.setText(_translate("MetroBookingForm", "Vé lượt"))
        self.lineDivider.setStyleSheet(_translate("MetroBookingForm", "color: #E0F2FE;"))
        self.s3.setStyleSheet(_translate("MetroBookingForm", "color:#0C4A6E; font-weight:600; font-size:13.5px;"))
        self.s3.setText(_translate("MetroBookingForm", "Số tiền"))
        self.sumTotal.setStyleSheet(_translate("MetroBookingForm", "color:#0369A1; font-weight:800; font-size:22px;"))
        self.sumTotal.setText(_translate("MetroBookingForm", "12.000 VNĐ"))
        self.lblBalance.setStyleSheet(_translate("MetroBookingForm", "color:#0284C7; font-size:12.5px; font-weight:500;"))
        self.lblBalance.setText(_translate("MetroBookingForm", "💳  Số dư: 500.000 VNĐ"))
        self.btnPay.setText(_translate("MetroBookingForm", "Xác nhận thanh toán ↗"))
