# Form implementation generated from reading ui file 'VeCuaToi.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VeCoiToiWindow(object):
    def setupUi(self, VeCoiToiWindow):
        VeCoiToiWindow.setObjectName("VeCoiToiWindow")
        VeCoiToiWindow.resize(440, 780)
        VeCoiToiWindow.setStyleSheet("\n"
"/* ── Nền tổng ── */\n"
"QWidget#centralwidget {\n"
"    background-color: #F0F9FF;\n"
"}\n"
"\n"
"/* ── Header ── */\n"
"QFrame#header {\n"
"    background-color: #FFFFFF;\n"
"    border-bottom: 1px solid #BAE6FD;\n"
"}\n"
"QLabel#lbl_title {\n"
"    color: #0C4A6E;\n"
"    font-size: 16px;\n"
"    font-weight: 700;\n"
"    font-family: \'Segoe UI\', system-ui, sans-serif;\n"
"}\n"
"QPushButton#btn_back {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #0284C7;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton#btn_back:hover {\n"
"    color: #0EA5E9;\n"
"}\n"
"\n"
"/* ── Filter tab bar ── */\n"
"QFrame#filterBar {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 12px;\n"
"    border: 1px solid #E0F2FE;\n"
"}\n"
"QPushButton#btnTabAll,\n"
"QPushButton#btnTabUnused,\n"
"QPushButton#btnTabUsed,\n"
"QPushButton#btnTabExpired {\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-size: 12px;\n"
"    font-weight: 600;\n"
"    padding: 6px 10px;\n"
"    background-color: transparent;\n"
"    color: #7DD3FC;\n"
"}\n"
"QPushButton#btnTabAll:hover,\n"
"QPushButton#btnTabUnused:hover,\n"
"QPushButton#btnTabUsed:hover,\n"
"QPushButton#btnTabExpired:hover {\n"
"    background-color: #F0F9FF;\n"
"    color: #0284C7;\n"
"}\n"
"\n"
"/* ── Scroll area ── */\n"
"QScrollArea {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"QScrollBar:vertical {\n"
"    width: 5px;\n"
"    background: #E0F2FE;\n"
"    border-radius: 3px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #7DD3FC;\n"
"    border-radius: 3px;\n"
"}\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"/* ── Empty state ── */\n"
"QLabel#lbl_empty {\n"
"    color: #93C5FD;\n"
"    font-size: 13px;\n"
"    font-family: \'Segoe UI\', system-ui, sans-serif;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=VeCoiToiWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rootLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.rootLayout.setContentsMargins(0, 0, 0, 0)
        self.rootLayout.setSpacing(0)
        self.rootLayout.setObjectName("rootLayout")
        self.header = QtWidgets.QFrame(parent=self.centralwidget)
        self.header.setMinimumSize(QtCore.QSize(0, 56))
        self.header.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.header.setObjectName("header")
        self.headerLayout = QtWidgets.QHBoxLayout(self.header)
        self.headerLayout.setContentsMargins(16, 10, 16, 10)
        self.headerLayout.setSpacing(10)
        self.headerLayout.setObjectName("headerLayout")
        self.btn_back = QtWidgets.QPushButton(parent=self.header)
        self.btn_back.setMaximumSize(QtCore.QSize(32, 32))
        self.btn_back.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_back.setObjectName("btn_back")
        self.headerLayout.addWidget(self.btn_back)
        self.lbl_title = QtWidgets.QLabel(parent=self.header)
        self.lbl_title.setObjectName("lbl_title")
        self.headerLayout.addWidget(self.lbl_title)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.lbl_count = QtWidgets.QLabel(parent=self.header)
        self.lbl_count.setObjectName("lbl_count")
        self.headerLayout.addWidget(self.lbl_count)
        self.rootLayout.addWidget(self.header)
        self.filterBar = QtWidgets.QFrame(parent=self.centralwidget)
        self.filterBar.setMaximumSize(QtCore.QSize(16777215, 48))
        self.filterBar.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.filterBar.setObjectName("filterBar")
        self.filterLayout = QtWidgets.QHBoxLayout(self.filterBar)
        self.filterLayout.setContentsMargins(16, 8, 16, 8)
        self.filterLayout.setSpacing(6)
        self.filterLayout.setObjectName("filterLayout")
        self.btnTabAll = QtWidgets.QPushButton(parent=self.filterBar)
        self.btnTabAll.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnTabAll.setObjectName("btnTabAll")
        self.filterLayout.addWidget(self.btnTabAll)
        self.btnTabUnused = QtWidgets.QPushButton(parent=self.filterBar)
        self.btnTabUnused.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnTabUnused.setObjectName("btnTabUnused")
        self.filterLayout.addWidget(self.btnTabUnused)
        self.btnTabUsed = QtWidgets.QPushButton(parent=self.filterBar)
        self.btnTabUsed.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnTabUsed.setObjectName("btnTabUsed")
        self.filterLayout.addWidget(self.btnTabUsed)
        self.btnTabExpired = QtWidgets.QPushButton(parent=self.filterBar)
        self.btnTabExpired.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnTabExpired.setObjectName("btnTabExpired")
        self.filterLayout.addWidget(self.btnTabExpired)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.filterLayout.addItem(spacerItem1)
        self.rootLayout.addWidget(self.filterBar)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollContents = QtWidgets.QWidget()
        self.scrollContents.setObjectName("scrollContents")
        self.ticketListLayout = QtWidgets.QVBoxLayout(self.scrollContents)
        self.ticketListLayout.setContentsMargins(16, 12, 16, 20)
        self.ticketListLayout.setSpacing(12)
        self.ticketListLayout.setObjectName("ticketListLayout")
        self.lbl_empty = QtWidgets.QLabel(parent=self.scrollContents)
        self.lbl_empty.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_empty.setVisible(False)
        self.lbl_empty.setObjectName("lbl_empty")
        self.ticketListLayout.addWidget(self.lbl_empty)
        spacerItem2 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.ticketListLayout.addItem(spacerItem2)
        self.scrollArea.setWidget(self.scrollContents)
        self.rootLayout.addWidget(self.scrollArea)
        VeCoiToiWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(VeCoiToiWindow)
        QtCore.QMetaObject.connectSlotsByName(VeCoiToiWindow)

    def retranslateUi(self, VeCoiToiWindow):
        _translate = QtCore.QCoreApplication.translate
        VeCoiToiWindow.setWindowTitle(_translate("VeCoiToiWindow", "Vé Của Tôi"))
        self.btn_back.setText(_translate("VeCoiToiWindow", "←"))
        self.lbl_title.setText(_translate("VeCoiToiWindow", "📱  Vé của tôi"))
        self.lbl_count.setStyleSheet(_translate("VeCoiToiWindow", "background-color:#E0F2FE; color:#0284C7; border-radius:10px;\n"
"font-size:12px; font-weight:600; padding: 3px 10px;"))
        self.lbl_count.setText(_translate("VeCoiToiWindow", "0 vé"))
        self.btnTabAll.setText(_translate("VeCoiToiWindow", "Tất cả"))
        self.btnTabUnused.setText(_translate("VeCoiToiWindow", "Chưa dùng"))
        self.btnTabUsed.setText(_translate("VeCoiToiWindow", "Đã dùng"))
        self.btnTabExpired.setText(_translate("VeCoiToiWindow", "Hết hạn"))
        self.scrollContents.setStyleSheet(_translate("VeCoiToiWindow", "QWidget#scrollContents { background: transparent; }"))
        self.lbl_empty.setText(_translate("VeCoiToiWindow", "Bạn chưa có vé nào."))
