USE Metro_Customer;
GO



SELECT * FROM [USER];
SELECT * FROM STATION;
SELECT * FROM ROUTE;
SELECT * FROM PAYMENT_METHOD;
SELECT * FROM TICKET_TYPE;
SELECT * FROM ROUTESTATION;
SELECT * FROM TRAIN;
SELECT * FROM WALLET;
SELECT * FROM PRICE_TABLE;
SELECT * FROM TICKET;
SELECT * FROM [TRANSACTION];
SELECT * FROM SCANNING_HISTORY;
SELECT * FROM REFUNDS;