# Form implementation generated from reading ui file 'D:\TuduylaptrinhN1\Session3\metro_admin_dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 703)
        MainWindow.setStyleSheet("\n"
"    QMainWindow {\n"
"        background-color: #EBF1F5;\n"
"    }\n"
"    #central_panel {\n"
"        background-color: #FFFFFF;\n"
"        border-radius: 16px;\n"
"    }\n"
"    QFrame#card_1, QFrame#card_2, QFrame#card_3, QFrame#card_4 {\n"
"        background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #2A5C91, stop:1 #1E436D);\n"
"        border-radius: 12px;\n"
"    }\n"
"    QFrame#card_1 QLabel, QFrame#card_2 QLabel, QFrame#card_3 QLabel, QFrame#card_4 QLabel {\n"
"        color: #FFFFFF;\n"
"    }\n"
"    QFrame#card_1 QPushButton, QFrame#card_2 QPushButton, QFrame#card_3 QPushButton, QFrame#card_4 QPushButton {\n"
"        background-color: rgba(255, 255, 255, 0.15);\n"
"        border: 1px solid rgba(255, 255, 255, 0.3);\n"
"        color: #FFFFFF;\n"
"        border-radius: 6px;\n"
"        padding: 6px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QFrame#card_1 QPushButton:hover, QFrame#card_2 QPushButton:hover, QFrame#card_3 QPushButton:hover, QFrame#card_4 QPushButton:hover {\n"
"        background-color: rgba(255, 255, 255, 0.25);\n"
"    }\n"
"    QLabel#lbl_quick_mgmt {\n"
"        color: #0A2540;\n"
"        font-weight: bold;\n"
"        font-size: 14px;\n"
"    }\n"
"    QPushButton.quick_btn {\n"
"        background-color: #F8FAFC;\n"
"        border: 1px solid #E2E8F0;\n"
"        border-radius: 10px;\n"
"        color: #0A2540;\n"
"        font-weight: bold;\n"
"        text-align: left;\n"
"        padding-left: 15px;\n"
"    }\n"
"    QPushButton.quick_btn:hover {\n"
"        background-color: #EDF2F7;\n"
"        border-color: #CBD5E0;\n"
"    }\n"
"    QFrame#footer_bar {\n"
"        background-color: #DCEEFB;\n"
"        border-radius: 8px;\n"
"    }\n"
"    QLabel#lbl_footer {\n"
"        color: #1A5276;\n"
"        font-size: 11px;\n"
"    }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.main_layout.setContentsMargins(15, 15, 15, 15)
        self.main_layout.setSpacing(12)
        self.main_layout.setObjectName("main_layout")
        self.central_panel = QtWidgets.QFrame(parent=self.centralwidget)
        self.central_panel.setStyleSheet("background-color: #F0FAFF ;")
        self.central_panel.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.central_panel.setObjectName("central_panel")
        self.panel_layout = QtWidgets.QVBoxLayout(self.central_panel)
        self.panel_layout.setContentsMargins(15, 15, 15, 15)
        self.panel_layout.setSpacing(15)
        self.panel_layout.setObjectName("panel_layout")
        self.header_top_layout = QtWidgets.QHBoxLayout()
        self.header_top_layout.setObjectName("header_top_layout")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.header_top_layout.addItem(spacerItem)
        self.btn_logout = QtWidgets.QPushButton(parent=self.central_panel)
        self.btn_logout.setStyleSheet("color: #0A4D7A;\n"
"padding: 4px 10px; border: 1px solid #CBD5E0; border-radius: 6px; color: #4A5568;\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.btn_logout.setObjectName("btn_logout")
        self.header_top_layout.addWidget(self.btn_logout)
        self.panel_layout.addLayout(self.header_top_layout)
        self.profile_layout = QtWidgets.QVBoxLayout()
        self.profile_layout.setSpacing(6)
        self.profile_layout.setObjectName("profile_layout")
        self.lbl_admin_title = QtWidgets.QLabel(parent=self.central_panel)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_admin_title.setFont(font)
        self.lbl_admin_title.setStyleSheet("color: #0A2540;\n"
"background-color: #E1F5FE;")
        self.lbl_admin_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_admin_title.setObjectName("lbl_admin_title")
        self.profile_layout.addWidget(self.lbl_admin_title)
        self.lbl_admin_email = QtWidgets.QLabel(parent=self.central_panel)
        self.lbl_admin_email.setStyleSheet("color: #627D98;\n"
"background-color: #E1F5FE;")
        self.lbl_admin_email.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_admin_email.setObjectName("lbl_admin_email")
        self.profile_layout.addWidget(self.lbl_admin_email)
        self.panel_layout.addLayout(self.profile_layout)
        self.cards_grid = QtWidgets.QGridLayout()
        self.cards_grid.setSpacing(10)
        self.cards_grid.setObjectName("cards_grid")
        self.card_1 = QtWidgets.QFrame(parent=self.central_panel)
        self.card_1.setStyleSheet("background-color: #29B6F6;")
        self.card_1.setObjectName("card_1")
        self.card_1_lay = QtWidgets.QVBoxLayout(self.card_1)
        self.card_1_lay.setObjectName("card_1_lay")
        self.c1_ico = QtWidgets.QLabel(parent=self.card_1)
        self.c1_ico.setObjectName("c1_ico")
        self.card_1_lay.addWidget(self.c1_ico)
        self.c1_num = QtWidgets.QLabel(parent=self.card_1)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.c1_num.setFont(font)
        self.c1_num.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.c1_num.setObjectName("c1_num")
        self.card_1_lay.addWidget(self.c1_num)
        self.c1_sub = QtWidgets.QLabel(parent=self.card_1)
        self.c1_sub.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.c1_sub.setObjectName("c1_sub")
        self.card_1_lay.addWidget(self.c1_sub)
        self.c1_btn = QtWidgets.QPushButton(parent=self.card_1)
        self.c1_btn.setStyleSheet("color: #0A4D7A;\n"
"background-color: rgb(255, 255, 255);")
        self.c1_btn.setObjectName("c1_btn")
        self.card_1_lay.addWidget(self.c1_btn)
        self.cards_grid.addWidget(self.card_1, 0, 0, 1, 1)
        self.card_2 = QtWidgets.QFrame(parent=self.central_panel)
        self.card_2.setStyleSheet("background-color: #29B6F6;")
        self.card_2.setObjectName("card_2")
        self.card_2_lay = QtWidgets.QVBoxLayout(self.card_2)
        self.card_2_lay.setObjectName("card_2_lay")
        self.c2_ico = QtWidgets.QLabel(parent=self.card_2)
        self.c2_ico.setObjectName("c2_ico")
        self.card_2_lay.addWidget(self.c2_ico)
        self.c2_num = QtWidgets.QLabel(parent=self.card_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.c2_num.setFont(font)
        self.c2_num.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.c2_num.setObjectName("c2_num")
        self.card_2_lay.addWidget(self.c2_num)
        self.c2_sub = QtWidgets.QLabel(parent=self.card_2)
        self.c2_sub.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.c2_sub.setObjectName("c2_sub")
        self.card_2_lay.addWidget(self.c2_sub)
        self.c2_btn = QtWidgets.QPushButton(parent=self.card_2)
        self.c2_btn.setStyleSheet("color: #0A4D7A;\n"
"background-color: rgb(255, 255, 255);")
        self.c2_btn.setObjectName("c2_btn")
        self.card_2_lay.addWidget(self.c2_btn)
        self.cards_grid.addWidget(self.card_2, 0, 1, 1, 1)
        self.card_3 = QtWidgets.QFrame(parent=self.central_panel)
        self.card_3.setStyleSheet("background-color: #29B6F6;")
        self.card_3.setObjectName("card_3")
        self.card_3_lay = QtWidgets.QVBoxLayout(self.card_3)
        self.card_3_lay.setObjectName("card_3_lay")
        self.c3_ico = QtWidgets.QLabel(parent=self.card_3)
        self.c3_ico.setObjectName("c3_ico")
        self.card_3_lay.addWidget(self.c3_ico)
        self.c3_num = QtWidgets.QLabel(parent=self.card_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.c3_num.setFont(font)
        self.c3_num.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.c3_num.setObjectName("c3_num")
        self.card_3_lay.addWidget(self.c3_num)
        self.c3_sub = QtWidgets.QLabel(parent=self.card_3)
        self.c3_sub.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.c3_sub.setObjectName("c3_sub")
        self.card_3_lay.addWidget(self.c3_sub)
        self.c3_btn = QtWidgets.QPushButton(parent=self.card_3)
        self.c3_btn.setStyleSheet("color: #0A4D7A;\n"
"background-color: rgb(255, 255, 255);")
        self.c3_btn.setObjectName("c3_btn")
        self.card_3_lay.addWidget(self.c3_btn)
        self.cards_grid.addWidget(self.card_3, 1, 0, 1, 1)
        self.card_4 = QtWidgets.QFrame(parent=self.central_panel)
        self.card_4.setStyleSheet("background-color: #29B6F6;")
        self.card_4.setObjectName("card_4")
        self.card_4_lay = QtWidgets.QVBoxLayout(self.card_4)
        self.card_4_lay.setObjectName("card_4_lay")
        self.c4_ico = QtWidgets.QLabel(parent=self.card_4)
        self.c4_ico.setObjectName("c4_ico")
        self.card_4_lay.addWidget(self.c4_ico)
        self.c4_num = QtWidgets.QLabel(parent=self.card_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.c4_num.setFont(font)
        self.c4_num.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.c4_num.setObjectName("c4_num")
        self.card_4_lay.addWidget(self.c4_num)
        self.c4_sub = QtWidgets.QLabel(parent=self.card_4)
        self.c4_sub.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.c4_sub.setObjectName("c4_sub")
        self.card_4_lay.addWidget(self.c4_sub)
        self.c4_btn = QtWidgets.QPushButton(parent=self.card_4)
        self.c4_btn.setStyleSheet("color: #0A4D7A;\n"
"background-color: rgb(255, 255, 255);")
        self.c4_btn.setObjectName("c4_btn")
        self.card_4_lay.addWidget(self.c4_btn)
        self.cards_grid.addWidget(self.card_4, 1, 1, 1, 1)
        self.panel_layout.addLayout(self.cards_grid)
        self.lbl_quick_mgmt = QtWidgets.QLabel(parent=self.central_panel)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lbl_quick_mgmt.setFont(font)
        self.lbl_quick_mgmt.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.lbl_quick_mgmt.setObjectName("lbl_quick_mgmt")
        self.panel_layout.addWidget(self.lbl_quick_mgmt)
        self.quick_grid = QtWidgets.QGridLayout()
        self.quick_grid.setSpacing(8)
        self.quick_grid.setObjectName("quick_grid")
        self.btn_tuyen_ga = QtWidgets.QPushButton(parent=self.central_panel)
        self.btn_tuyen_ga.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_tuyen_ga.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: #0A4D7A;\n"
"background-color: rgb(255, 255, 255);")
        self.btn_tuyen_ga.setObjectName("btn_tuyen_ga")
        self.quick_grid.addWidget(self.btn_tuyen_ga, 0, 0, 1, 1)
        self.btn_bao_cao = QtWidgets.QPushButton(parent=self.central_panel)
        self.btn_bao_cao.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_bao_cao.setStyleSheet("color: #0A4D7A;\n"
"background-color: rgb(255, 255, 255);font: 10pt \"MS Shell Dlg 2\";")
        self.btn_bao_cao.setObjectName("btn_bao_cao")
        self.quick_grid.addWidget(self.btn_bao_cao, 1, 1, 1, 1)
        self.btn_tai_khoan = QtWidgets.QPushButton(parent=self.central_panel)
        self.btn_tai_khoan.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_tai_khoan.setStyleSheet("color: #0A4D7A;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.btn_tai_khoan.setObjectName("btn_tai_khoan")
        self.quick_grid.addWidget(self.btn_tai_khoan, 0, 1, 1, 1)
        self.btn_bang_gia = QtWidgets.QPushButton(parent=self.central_panel)
        self.btn_bang_gia.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_bang_gia.setStyleSheet("color: #0A4D7A;\n"
"background-color: rgb(255, 255, 255);font: 10pt \"MS Shell Dlg 2\";")
        self.btn_bang_gia.setObjectName("btn_bang_gia")
        self.quick_grid.addWidget(self.btn_bang_gia, 1, 0, 1, 1)
        self.panel_layout.addLayout(self.quick_grid)
        self.footer_bar = QtWidgets.QFrame(parent=self.central_panel)
        self.footer_bar.setStyleSheet("background-color: #E1F5FE;")
        self.footer_bar.setObjectName("footer_bar")
        self.footer_lay = QtWidgets.QHBoxLayout(self.footer_bar)
        self.footer_lay.setContentsMargins(-1, 8, -1, 8)
        self.footer_lay.setObjectName("footer_lay")
        self.lbl_footer = QtWidgets.QLabel(parent=self.footer_bar)
        self.lbl_footer.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lbl_footer.setObjectName("lbl_footer")
        self.footer_lay.addWidget(self.lbl_footer)
        self.panel_layout.addWidget(self.footer_bar)
        self.main_layout.addWidget(self.central_panel)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Metro Ticket Admin Dashboard"))
        self.btn_logout.setText(_translate("MainWindow", "  Đăng xuất"))
        self.lbl_admin_title.setText(_translate("MainWindow", "Quản trị viên"))
        self.lbl_admin_email.setText(_translate("MainWindow", "admin.aradhm@metro.vn"))
        self.c1_ico.setText(_translate("MainWindow", "🤝 Yêu cầu nạp tiền"))
        self.c1_num.setText(_translate("MainWindow", "12"))
        self.c1_sub.setText(_translate("MainWindow", "Chờ xử lý"))
        self.c1_btn.setText(_translate("MainWindow", "Xem danh sách"))
        self.c2_ico.setText(_translate("MainWindow", "🚇 Chuyến tàu đang chạy"))
        self.c2_num.setText(_translate("MainWindow", "8"))
        self.c2_sub.setText(_translate("MainWindow", "Active / 2 Maintenance"))
        self.c2_btn.setText(_translate("MainWindow", "Quản lý chuyến"))
        self.c3_ico.setText(_translate("MainWindow", "🎫 Vé lượt bán hôm nay"))
        self.c3_num.setText(_translate("MainWindow", "4,567"))
        self.c3_sub.setText(_translate("MainWindow", "Vé"))
        self.c3_btn.setText(_translate("MainWindow", "Xem báo cáo"))
        self.c4_ico.setText(_translate("MainWindow", "⭕ Yêu cầu hoàn tiền"))
        self.c4_num.setText(_translate("MainWindow", "3"))
        self.c4_sub.setText(_translate("MainWindow", "Chờ xử lý"))
        self.c4_btn.setText(_translate("MainWindow", "Xử lý ngay"))
        self.lbl_quick_mgmt.setText(_translate("MainWindow", "Quản lý nhanh"))
        self.btn_tuyen_ga.setText(_translate("MainWindow", "🌿  Tuyến & Ga"))
        self.btn_bao_cao.setText(_translate("MainWindow", "📊  Báo cáo"))
        self.btn_tai_khoan.setText(_translate("MainWindow", "👤  Tài khoản (Users)"))
        self.btn_bang_gia.setText(_translate("MainWindow", "💰  Bảng giá"))
        self.lbl_footer.setText(_translate("MainWindow", "ℹ️ Hệ thống tự động ghi nhật ký admin."))
